#!/usr/bin/env python3
"""Writes 3ds/core/pd_map_gen.c from the app's region-map tables:

- the fingerprints RomArt finds the region map's art by in a ROM
  (RomArtSigsGen.kt - only the blobs the 3DS MAP needs),
- the cursor grids (RegionMapLayoutsGen.kt),
- every map section's page and rectangle (MapSecData*.kt).

    python3 3ds/tools/gen_map_tables.py
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA = os.path.join(ROOT, "app/src/main/kotlin/com/pokedaisy/app/companion/data")
OUT = os.path.join(ROOT, "3ds/core/pd_map_gen.c")

BLOBS = [
    "FR_REGION_GFX", "FR_REGION_PAL", "FR_KANTO_MAP", "FR_SEVII123_MAP", "FR_SEVII45_MAP", "FR_SEVII67_MAP",
    "FR_PLAYER_RED_GFX", "FR_PLAYER_LEAF_GFX", "FR_PLAYER_PAL",
    "EM_REGION_GFX", "EM_REGION_PAL", "EM_REGION_MAP",
    "EM_PLAYER_BRENDAN_GFX", "EM_PLAYER_BRENDAN_PAL", "EM_PLAYER_MAY_GFX", "EM_PLAYER_MAY_PAL",
]


def read(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return f.read()


def blobs():
    text = read("RomArtSigsGen.kt")
    out = []
    for name in BLOBS:
        m = re.search(r"\b" + name + r"\((true|false), (\d+), (0x[0-9A-F]+)L, (\d+), (-?\d+)L, (0x[0-9A-F]+)", text)
        if not m:
            raise SystemExit(f"gen_map_tables: no {name} in RomArtSigsGen.kt")
        lz, size, crc, head_off, head, pre = m.groups()
        out.append((name, lz == "true", int(size), int(crc, 16), int(head_off), int(head) & (2**64 - 1), int(pre, 16)))
    return out


def layouts():
    text = read("RegionMapLayoutsGen.kt")
    result = {}
    for game, decl in (("firered", "regionLayoutsFireRed"), ("emerald", "regionLayoutsEmerald")):
        body = text[text.index(f"val {decl}"):]
        body = body[:body.index("\n)\n")]
        pages = []
        for m in re.finditer(r"RegionLayout\((\d+), (\d+), (\d+), (\d+), (0x[0-9A-F]+), listOf\((.*?)\)\)", body, re.S):
            off_x, off_y, w, h, none, layers = m.groups()
            hexes = re.findall(r'hexBytes\("([0-9a-f]+)"\)', layers)
            pages.append((int(off_x), int(off_y), int(w), int(h), int(none, 16), [bytes.fromhex(x) for x in hexes]))
        result[game] = pages
    return result


def mapsecs(name, decl):
    text = read(name)
    body = text[text.index(f"val {decl}"):]
    body = body[:body.index("\n)\n")]
    return {int(k): (int(r), int(x), int(y), int(w), int(h)) for k, r, x, y, w, h in re.findall(
        r'(\d+) to MapSecInfo\("[^"]*", (-?\d+), (\d+), (\d+), (\d+), (\d+)\)', body)}


def c_bytes(data):
    lines = []
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 24]) + ",")
    return "\n".join(lines)


def main():
    out = [
        "// Generated by 3ds/tools/gen_map_tables.py from the app's RomArtSigsGen.kt,",
        "// RegionMapLayoutsGen.kt and MapSecData*.kt - do not hand-edit.",
        '#include "pd_map.h"',
        "",
        "const struct pd_blob_sig pd_blob_sigs[PD_BLOB_COUNT] = {",
    ]
    for name, lz, size, crc, head_off, head, pre in blobs():
        out.append(f"    [PD_{name}] = {{ {str(lz).lower()}, {size}, 0x{crc:08X}u, {head_off}, 0x{head:016X}ull, 0x{pre:04X} }},")
    out.append("};")
    out.append("")

    lay = layouts()
    for game, pages in lay.items():
        for i, (ox, oy, w, h, none, layers) in enumerate(pages):
            for l, data in enumerate(layers):
                assert len(data) == w * h, (game, i, l, len(data))
                out.append(f"static const unsigned char {game}_layout{i}_{l}[{len(data)}] = {{")
                out.append(c_bytes(data))
                out.append("};")
        out.append(f"const struct pd_region_layout pd_layouts_{game}[{len(pages)}] = {{")
        for i, (ox, oy, w, h, none, layers) in enumerate(pages):
            l1 = f"{game}_layout{i}_1" if len(layers) > 1 else "NULL"
            out.append(f"    {{ {ox}, {oy}, {w}, {h}, 0x{none:02X}, {{ {game}_layout{i}_0, {l1} }} }},")
        out.append("};")
        out.append(f"const int pd_layouts_{game}_count = {len(pages)};")
        out.append("")

    for game, name, decl in (("firered", "MapSecData.kt", "mapSecData"),
                             ("emerald", "MapSecDataEmerald.kt", "mapSecDataEmerald")):
        secs = mapsecs(name, decl)
        top = max(secs) + 1
        out.append(f"const struct pd_mapsec_rect pd_mapsec_rects_{game}[{top}] = {{")
        for i in range(top):
            if i in secs:
                r, x, y, w, h = secs[i]
                out.append(f"    {{ {r}, {x}, {y}, {w}, {h} }},")
            else:
                out.append("    { -1, 0, 0, 0, 0 },")
        out.append("};")
        out.append(f"const int pd_mapsec_rects_{game}_count = {top};")
        out.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(BLOBS)} blobs, "
          f"{len(lay['firered'])}+{len(lay['emerald'])} layouts")


if __name__ == "__main__":
    main()
