#!/usr/bin/env python3
"""Writes 3ds/ctr/icon.png, the 48x48 HOME Menu icon, from the app's own
launcher icon: its foreground (app/src/main/res/mipmap-xxxhdpi/
ic_launcher_foreground.png, generated by scripts/gen_logo.mjs) over the
launcher's blue background, cropped to the adaptive icon's visible middle.

    python3 3ds/tools/gen_icon.py      (needs Pillow)
"""
import os
import re

from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
FG = os.path.join(ROOT, "app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png")
BG_XML = os.path.join(ROOT, "app/src/main/res/values/ic_launcher_background.xml")
OUT = os.path.join(ROOT, "3ds/ctr/icon.png")


def main():
    with open(BG_XML) as f:
        bg = re.search(r"#([0-9a-fA-F]{6})", f.read()).group(1)
    fg = Image.open(FG).convert("RGBA")
    # An adaptive icon shows the middle 72 of its 108 dp.
    w, h = fg.size
    inset = w * 18 // 108
    fg = fg.crop((inset, inset, w - inset, h - inset))
    icon = Image.new("RGBA", fg.size, "#" + bg)
    icon.alpha_composite(fg)
    icon.convert("RGB").resize((48, 48), Image.LANCZOS).save(OUT)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
