#!/usr/bin/env python3
"""Writes 3ds/core/pd_font_gen.c: Pixel Operator (the app's only font,
app/src/main/assets/fonts/PixelOperator.ttf, CC0) as a 1-bit bitmap font.

Pixel Operator is drawn on a 100-unit pixel at 1600 units per em, so at 16 px
every font pixel is exactly one screen pixel - the same crisp glyphs the app
draws, with no TrueType renderer needed on the 3DS. Each glyph is a 16-row
cell (ascent 13, descent 3); a row is a bitmask, bit 0 = leftmost pixel.

    python3 3ds/tools/gen_font.py      (needs Pillow)
"""
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TTF = os.path.join(ROOT, "app/src/main/assets/fonts/PixelOperator.ttf")
OUT = os.path.join(ROOT, "3ds/core/pd_font_gen.c")

SIZE = 16
# Rasterized this many times larger and sampled at each pixel's centre: at
# 16 px FreeType's hinting breaks diagonal strokes (é's accent got a gap).
SCALE = 10
# ASCII plus the few non-ASCII letters the names use (Poké Ball, Pokémon ...).
EXTRA = "é×"
CHARS = [chr(c) for c in range(32, 127)] + list(EXTRA)

# Pixel Operator has no gender symbols; these are drawn here, on the font's
# cap rows (4-12), for the party's gender marks and Nidoran's names.
PIXEL_GLYPHS = {
    "♂": (8, [
        "....###",
        ".....##",
        "....#.#",
        ".###...",
        "#...#..",
        "#...#..",
        "#...#..",
        ".###...",
        ".......",
    ]),
    "♀": (6, [
        ".###.",
        "#...#",
        "#...#",
        "#...#",
        ".###.",
        "..#..",
        "#####",
        "..#..",
        "..#..",
    ]),
}
CAP_TOP = 4


def main():
    font = ImageFont.truetype(TTF, SIZE * SCALE)
    ascent, descent = font.getmetrics()
    assert ascent + descent == SIZE * SCALE, (ascent, descent)
    out = [
        "// Generated by 3ds/tools/gen_font.py from PixelOperator.ttf (CC0) - do not hand-edit.",
        '#include "pd_font.h"',
        "",
        f"const struct pd_glyph pd_font_glyphs[{len(CHARS) + len(PIXEL_GLYPHS)}] = {{",
    ]
    for ch in CHARS:
        advance = round(font.getlength(ch) / SCALE)
        im = Image.new("L", (16 * SCALE, SIZE * SCALE), 0)
        ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=255)
        rows = [0] * SIZE
        for y in range(SIZE):
            for x in range(16):
                if im.getpixel((x * SCALE + SCALE // 2, y * SCALE + SCALE // 2)) > 127:
                    rows[y] |= 1 << x
        desc = "space" if ch == " " else ch.replace("\\", "backslash")
        out.append(f"    {{ 0x{ord(ch):04X}, {advance}, {{ {', '.join(f'0x{r:04X}' for r in rows)} }} }}, // {desc}")
    for ch, (advance, art) in PIXEL_GLYPHS.items():
        rows = [0] * SIZE
        for y, line in enumerate(art):
            for x, px in enumerate(line):
                if px == "#":
                    rows[CAP_TOP + y] |= 1 << x
        out.append(f"    {{ 0x{ord(ch):04X}, {advance}, {{ {', '.join(f'0x{r:04X}' for r in rows)} }} }}, // {ch} (drawn)")
    out.append("};")
    out.append(f"const int pd_font_glyph_count = {len(CHARS) + len(PIXEL_GLYPHS)};")
    out.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(CHARS) + len(PIXEL_GLYPHS)} glyphs")


if __name__ == "__main__":
    main()
