#!/usr/bin/env python3
"""Writes 3ds/core/pd_tables_gen.c from the Android app's own Kotlin tables.

The app's tables are the source of truth (species, moves, type chart, map
sections); this only re-emits them as C arrays so the 3DS build never drifts
from them. Rerun after changing any of the files in SOURCES:

    python3 3ds/tools/gen_tables.py
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA = os.path.join(ROOT, "app/src/main/kotlin/com/pokedaisy/app/companion/data")
OUT = os.path.join(ROOT, "3ds/core/pd_tables_gen.c")

SOURCES = {
    "species": "SpeciesNames.kt",
    "moves": "MoveData.kt",
    "types": "TypeChartUtil.kt",
    "chart": "TypeChart.kt",
    "mapsec_firered": "MapSecData.kt",
    "mapsec_emerald": "MapSecDataEmerald.kt",
    # Item names and descriptions exactly as each game's bag prints them.
    "items": "ItemTextGame.kt",
    "gender": "GenderRatiosFireRed.kt",
    "species_types": "SpeciesTypes.kt",
}


def read(name):
    with open(os.path.join(DATA, SOURCES[name]), encoding="utf-8") as f:
        return f.read()


def block(text, decl):
    """The body of `val <decl> ... = mapOf( ... )`."""
    m = re.search(r"val " + re.escape(decl) + r"\b[^=]*=\s*mapOf\((.*?)\n\)", text, re.S)
    if not m:
        sys.exit(f"gen_tables: no `val {decl}` table found")
    return m.group(1)


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def name_array(c_name, entries):
    top = max(entries)
    lines = [f"const char* const {c_name}[{top + 1}] = {{"]
    for i in range(top + 1):
        lines.append(f"    {c_str(entries[i]) if i in entries else 'NULL'},")
    lines.append("};")
    lines.append(f"const int {c_name}_count = {top + 1};")
    return "\n".join(lines)


def main():
    species = {int(k): v for k, v in re.findall(r'(\d+) to "([^"]*)"', block(read("species"), "speciesNames"))}

    moves = {}
    for k, body in re.findall(r"(\d+) to MoveInfo\(([^)]*)\)", block(read("moves"), "moveData")):
        m = re.match(r'"([^"]*)"\s*,\s*(\d+)(?:\s*,\s*(\d+))?', body)
        moves[int(k)] = (m.group(1), int(m.group(2)), int(m.group(3) or 0))

    types = {int(k): v for k, v in re.findall(r'(\d+) to "([^"]*)"', block(read("types"), "typeNames"))}

    chart = [(int(k), int(v)) for k, v in re.findall(r"(\d+) to (\d+)", block(read("chart"), "typeEffectiveness"))]

    # In capitals with a small é, like the app's gameCase() for FireRed / Emerald.
    def mapsecs(name, decl):
        return {int(k): "".join(c if c == "é" else c.upper() for c in v)
                for k, v in re.findall(r'(\d+) to MapSecInfo\("([^"]*)"', block(read(name), decl))}

    fr_secs = mapsecs("mapsec_firered", "mapSecData")
    em_secs = mapsecs("mapsec_emerald", "mapSecDataEmerald")

    def strings(name, decl):
        return {int(k): v for k, v in re.findall(r'(\d+) to "([^"]*)"', block(read(name), decl))}

    item_tables = [
        ("pd_item_names_firered", strings("items", "itemNamesFireRedGame")),
        ("pd_item_desc_firered", strings("items", "itemDescriptionsFireRedGame")),
        ("pd_item_names_emerald", strings("items", "itemNamesEmeraldGame")),
        ("pd_item_desc_emerald", strings("items", "itemDescriptionsEmeraldGame")),
    ]

    # Each species' two types (the same twice for one type), by internal id.
    species_types = {int(k): (int(a), int(b)) for k, a, b in
                     re.findall(r"(\d+) to SpeciesTypes\((\d+), (\d+)\)", block(read("species_types"), "speciesTypeData"))}
    # The app's table files BULBASAUR's types under 0 (no species) and has no 1.
    if 0 in species_types and 1 not in species_types:
        species_types[1] = species_types.pop(0)

    m = re.search(r"val genderRatiosFireRed = intArrayOf\(([^)]*)\)", read("gender"))
    gender = [int(v) for v in m.group(1).split(",")]

    out = [
        "// Generated by 3ds/tools/gen_tables.py from the app's Kotlin tables",
        "// (" + ", ".join(sorted(SOURCES.values())) + ") - do not hand-edit.",
        '#include "pd_tables.h"',
        "",
        name_array("pd_species_names", species),
        "",
    ]
    top = max(moves)
    out.append(f"const struct pd_move_info pd_moves[{top + 1}] = {{")
    for i in range(top + 1):
        if i in moves:
            n, t, p = moves[i]
            out.append(f"    {{ {c_str(n)}, {t}, {p} }},")
        else:
            out.append("    { NULL, 0, 0 },")
    out.append("};")
    out.append(f"const int pd_moves_count = {top + 1};")
    out.append("")
    out.append(name_array("pd_type_names", types))
    out.append("")
    out.append(f"const struct pd_type_pair pd_type_chart[{len(chart)}] = {{")
    for k, v in chart:
        out.append(f"    {{ {k // 100}, {k % 100}, {v} }},")
    out.append("};")
    out.append(f"const int pd_type_chart_count = {len(chart)};")
    out.append("")
    out.append(name_array("pd_mapsec_firered", fr_secs))
    out.append("")
    out.append(name_array("pd_mapsec_emerald", em_secs))
    out.append("")
    for c_name, table in item_tables:
        out.append(name_array(c_name, table))
        out.append("")
    out.append(f"const unsigned char pd_gender_ratios[{len(gender)}] = {{")
    for i in range(0, len(gender), 20):
        out.append("    " + ", ".join(str(v) for v in gender[i:i + 20]) + ",")
    out.append("};")
    out.append(f"const int pd_gender_ratios_count = {len(gender)};")
    out.append("")
    top = max(species_types)
    out.append(f"const unsigned char pd_species_type_table[{top + 1}][2] = {{")
    for i in range(top + 1):
        a, b = species_types.get(i, (255, 255))
        out.append(f"    {{ {a}, {b} }},")
    out.append("};")
    out.append(f"const int pd_species_type_table_count = {top + 1};")
    out.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(species)} species, {len(moves)} moves, "
          f"{len(chart)} chart entries, {len(fr_secs)}/{len(em_secs)} map sections, "
          f"{len(item_tables[0][1])}/{len(item_tables[2][1])} items, {len(gender)} gender ratios")


if __name__ == "__main__":
    main()
