package com.pokedaisey.app.companion.data

/**
 * Which game the app is currently reading. FireRed QoL exports a packed
 * gQolTelemetry struct (decodeTelemetry); Pokémon Unbound has none, so it's
 * read from native RAM (UnboundReader) with its own data tables extracted from
 * the Unbound ROM (*Unbound.kt, generated by
 * tools/telemetry-viewer/scripts/gen_unbound_data.py). Mirrors
 * tools/telemetry-viewer/game.go.
 */
// EMERALD shares FireRed's Gen 3 species/move/item/type tables (same internal
// indices) but has its own Hoenn region map + map-section names. GAIA and
// RADICAL_RED are FireRed-based hacks read the same way as vanilla FireRed
// (NATIVE_GAIA_V3_2 / NATIVE_RADICAL_RED_V4_1 in NativeReader.kt). Gaia
// relocated + grew its species table wholesale (see SpeciesNamesGaia.kt).
// Radical Red instead keeps ids 1-411 exactly where vanilla has them and
// appends its (huge - Gen 1-9 plus regional/Paradox/Ogerpon forms) custom
// dex past that in a second table, keyed by national dex number - so
// speciesNamesRadicalRed only needs to hold the extra ids and gets merged
// on top of the shared vanilla table instead of replacing it.
// ODYSSEY - basic connectivity only so far (NATIVE_ODYSSEY inherits every
// vanilla FireRed RAM address unchanged, unverified beyond a live party/item
// check - see NativeReader.kt). Whether it renumbers species/items enough to
// need its own name tables (like Gaia/Radical Red did) hasn't been checked yet -
// falls through to the shared vanilla tables below (`else`) until it has.
// HEART_AND_SOUL/LAZARUS/ROWE are Emerald-based hacks (BPEE) - the first ones
// this project has supported; same "inherit NATIVE_EMERALD unchanged, verify
// live, re-derive only what's actually broken" starting point as the FireRed
// hacks above, via NATIVE_HEART_AND_SOUL/NATIVE_LAZARUS/NATIVE_ROWE in
// NativeReader.kt. Heart and Soul and Lazarus now have their own
// ROM-extracted tables (*Hns.kt / *Lazarus.kt, scripts/gen_expansion_tables.py).
enum class GameKind { FIRERED, EMERALD, UNBOUND, GAIA, RADICAL_RED, ODYSSEY, HEART_AND_SOUL, LAZARUS, ROWE, EMERALD_ROGUE, AMETHYST, EMERALD_SEAGLASS, CELIA, TMT2 }

@Volatile
var activeGame: GameKind = GameKind.FIRERED

private inline val unbound get() = activeGame == GameKind.UNBOUND
private inline val emerald get() = activeGame == GameKind.EMERALD
private inline val seaglass get() = activeGame == GameKind.EMERALD_SEAGLASS
private inline val celia get() = activeGame == GameKind.CELIA
private inline val tmt2 get() = activeGame == GameKind.TMT2
private inline val hns get() = activeGame == GameKind.HEART_AND_SOUL
private inline val lazarus get() = activeGame == GameKind.LAZARUS
private inline val gaia get() = activeGame == GameKind.GAIA
private inline val radicalRed get() = activeGame == GameKind.RADICAL_RED
private inline val amethyst get() = activeGame == GameKind.AMETHYST
private inline val odyssey get() = activeGame == GameKind.ODYSSEY
// CFRU-family hacks with CFRU's own type ids (Fairy = 23, as in Unbound) -
// checked in each ROM's base stats (CLEFAIRY is 23/23).
private inline val cfruTypes get() = radicalRed || amethyst || gaia
// Hacks confirmed to store species as the plain National Dex number (see
// SpeciesNamesNationalDex.kt) rather than vanilla's internal Gen3 index.
private inline val nationalDexSpecies get() =
    activeGame == GameKind.EMERALD_ROGUE || activeGame == GameKind.EMERALD_SEAGLASS
// Hacks confirmed to renumber items vs vanilla with no id->name table of
// their own yet - fall back to itemName()'s "Item#N" default rather than
// showing a wrong vanilla name that happens to share the numeric id
// (confirmed wrong for Lazarus: its real item id 28 isn't vanilla's
// "Lemonade").
private inline val rogue get() = activeGame == GameKind.EMERALD_ROGUE

// Odyssey reuses vanilla's unused "???" type (9) as Fairy (CLEFAIRY is 9/9).
private val typeNamesOdyssey: Map<Int, String> by lazy { typeNames + (9 to "Fairy") }

private val speciesNamesRadicalRedMerged: Map<Int, String> by lazy { speciesNames + speciesNamesRadicalRed }
private val speciesNamesOdysseyMerged: Map<Int, String> by lazy { speciesNames + speciesNamesOdyssey }

val activeSpeciesNames: Map<Int, String> get() = when {
    unbound -> speciesNamesUnbound
    gaia -> speciesNamesGaia
    radicalRed -> speciesNamesRadicalRedMerged
    odyssey -> speciesNamesOdysseyMerged
    nationalDexSpecies -> speciesNamesNationalDex
    amethyst -> speciesNamesAmethyst
    celia -> speciesNamesCelia
    tmt2 -> speciesNamesTmt2
    hns -> speciesNamesHns
    lazarus -> speciesNamesLazarus
    else -> speciesNames
}
val activeMoveData: Map<Int, MoveInfo> get() = when {
    unbound -> moveDataUnbound
    celia -> moveDataCelia
    tmt2 -> moveDataTmt2
    hns -> moveDataHns
    lazarus -> moveDataLazarus
    rogue -> moveDataRogue
    else -> moveData
}
val activeItemNames: Map<Int, String> get() = when {
    unbound -> itemNamesUnbound
    amethyst -> itemNamesAmethyst
    seaglass -> itemNamesSeaglass
    celia -> itemNamesCelia
    tmt2 -> itemNamesTmt2
    hns -> itemNamesHns
    lazarus -> itemNamesLazarus
    rogue -> itemNamesRogue
    else -> itemNames
}
val activeSpeciesTypeData: Map<Int, SpeciesTypes> get() = when {
    unbound -> speciesTypeDataUnbound
    tmt2 -> speciesTypeDataTmt2
    hns -> speciesTypeDataHns
    lazarus -> speciesTypeDataLazarus
    celia -> speciesTypeDataCelia
    rogue -> speciesTypeDataRogue
    else -> speciesTypeData
}
val activeTypeEffectiveness: Map<Int, Int> get() = when {
    unbound || cfruTypes -> typeEffectivenessUnbound
    // Seaglass uses the standard expansion type ids (TORCHIC is 11 = Fire), as Heart and Soul does.
    seaglass -> typeEffectivenessHns
    tmt2 -> typeEffectivenessTmt2
    hns -> typeEffectivenessHns
    lazarus -> typeEffectivenessLazarus
    celia -> typeEffectivenessCelia
    rogue -> typeEffectivenessRogue
    else -> typeEffectiveness
}
val activeTypeNames: Map<Int, String> get() = when {
    unbound || cfruTypes -> typeNamesUnbound
    odyssey -> typeNamesOdyssey
    seaglass -> typeNamesHns
    tmt2 -> typeNamesTmt2
    hns -> typeNamesHns
    lazarus -> typeNamesLazarus
    celia -> typeNamesCelia
    rogue -> typeNamesRogue
    else -> typeNames
}
val activeMapSecData: Map<Int, MapSecInfo> get() = when {
    unbound -> mapSecDataUnbound
    // Seaglass keeps vanilla Hoenn mapsec ids (0x00 = Littleroot, confirmed live).
    emerald || seaglass || tmt2 -> mapSecDataEmerald
    // Own regions' names, text-only (no region-map image yet).
    hns -> mapSecDataHns
    lazarus -> mapSecDataLazarus
    rogue -> mapSecDataRogue
    else -> mapSecData
}
val activeRegionMapImages: Array<String> get() = when {
    unbound -> regionMapImagesUnbound
    emerald || seaglass || tmt2 -> regionMapImagesEmerald
    hns -> regionMapImagesHns
    lazarus -> regionMapImagesLazarus
    rogue -> regionMapImagesRogue
    else -> regionMapImages
}

/**
 * Unbound reindexes species/items vs vanilla so the bundled Gen 3 PNGs don't
 * match it. Mon + item icons are fetched live from the running game and cached
 * (UnboundIconSource), like its region map (RomRegionMap).
 */
val activeMonSpriteDir: String get() = if (unbound) "pokemon-unbound" else "pokemon"
val activeItemSpriteDir: String? get() = if (unbound) "items-unbound" else "items"

fun parseGameKind(s: String?): GameKind =
    if (s.equals("unbound", ignoreCase = true)) GameKind.UNBOUND else GameKind.FIRERED

/** Human-readable label for the Settings screen ("current game" display) -
 * distinct from the enum's own name (RADICAL_RED, not "Radical Red"). */
fun GameKind.displayName(): String = when (this) {
    GameKind.FIRERED -> "FireRed"
    GameKind.EMERALD -> "Emerald"
    GameKind.UNBOUND -> "Pokémon Unbound"
    GameKind.GAIA -> "Pokémon Gaia"
    GameKind.RADICAL_RED -> "Pokémon Radical Red"
    GameKind.ODYSSEY -> "Pokémon Odyssey"
    GameKind.HEART_AND_SOUL -> "Pokémon Heart and Soul"
    GameKind.LAZARUS -> "Pokémon Lazarus"
    GameKind.ROWE -> "Pokémon R.O.W.E."
    GameKind.EMERALD_ROGUE -> "Emerald Rogue"
    GameKind.AMETHYST -> "Pokémon Amethyst"
    GameKind.EMERALD_SEAGLASS -> "Emerald Seaglass"
    GameKind.CELIA -> "Celia's Stupid Romhack"
    GameKind.TMT2 -> "Too Many Types 2"
}
