// Generated by scripts/gen_logo.mjs from website/src/lib/pixel.js - don't edit by hand.
package com.pokedaisy.app.companion.ui

import androidx.compose.ui.graphics.Color

/** The PokeDaisy mark (a daisy drawn as a Poké Ball), for [PixelArt] with [LOGO_PALETTE]. */
val LOGO_ROWS = listOf(
    "..............KKKK..............",
    ".............KHHHDK.............",
    "............KHHRRRDK............",
    ".....KKK....KHRRRRDK....KKK.....",
    "....KHHDKK..KHRRRRDK..KKHHDK....",
    "...KHHRRRDK.KHRRRRDK.KHHHRRDK...",
    "...KHRRRRRDKKHRRRRDKKHHRRRRDK...",
    "...KDRRRRRRDKHRRRRDKHHRRRRDDK...",
    "....KRRRRRRRKDRRRDKHHRRRRRDK....",
    "....KDRRRRRRDKDDDDKHRRRRRDDK....",
    ".....KDRRRDDDKKKKKKDDRRRDDK.....",
    "......KDRRDKKyyYYYYKKRRDDK......",
    "..KKKKKKDDDKyyyYYYYYKDDDKKKKKK..",
    ".KHHHHHHKKKyyyKKKKYYYKKKHHHHHDK.",
    "KHHRRRRRRDKyyKKwwKKYYKHHRRRRRRDK",
    "KKKKKKKKKKKYYKwwwwKYYKKKKKKKKKKK",
    "KKKKKKKKKKKYYKwwwwKYYKKKKKKKKKKK",
    "KSWWWWWWSSKYYKKwwKKYYKSWWWWWWSSK",
    ".KSSSSSSSKKYYYKKKKYYYKKKSSSSSSK.",
    "..KKKKKKKWSKYYYYYYYYKWWSKKKKKK..",
    "......KWWWSKKYYYYYYKKWWWSK......",
    ".....KWWWWWWSKKKKKKWWWWWWSK.....",
    "....KWWWWWWWSKWWWSKWWWWWWWSK....",
    "....KWWWWWWSSKWWWWSKWWWWWWSK....",
    "...KWWWWWWSSKWWWWWSKSWWWWWWSK...",
    "...KWWWWWSSKKWWWWWSKKSWWWWWSK...",
    "...KSWWSSSK.KWWWWWSK.KSSWWSSK...",
    "....KSSSKK..KWWWWWSK..KKSSSK....",
    ".....KKK....KWWWWWSK....KKK.....",
    "............KSWWWSSK............",
    ".............KSSSSK.............",
    "..............KKKK..............",
)

val LOGO_PALETTE = mapOf(
    'K' to Color(0xFF202020),
    'R' to Color(0xFFE83028),
    'D' to Color(0xFFB01C14),
    'H' to Color(0xFFFF9080),
    'W' to Color(0xFFFFFFFF),
    'S' to Color(0xFFC4C8D4),
    'Y' to Color(0xFFF8D030),
    'y' to Color(0xFFFFF0A0),
    'w' to Color(0xFFFFF8D8),
)
