#!/usr/bin/env python3
"""PokeDaisy's Emerald Rogue v2.2.1-EX display tables, straight from the ROM
the user owns (nothing is downloaded):

    scripts/gen_rogue_tables.py <Pokemon Emerald Rogue (v2.2.1-EX).gba>

Writes ItemNamesRogue.kt, ItemDescriptionsRogue.kt, MapSecDataRogue.kt,
MoveDataRogue.kt, SpeciesTypesRogue.kt and TypeChartRogue.kt under
app/src/main/kotlin/.../companion/data.

Rogue (Pokabbie/pokeemerald-rogue, `expansion` branch = v2.2.1) mixes vanilla
and expansion shapes, so it isn't a gen_expansion_tables.py entry. Addresses
found in the ROM, layouts read from that source:
  - gItems: vanilla `struct Item` grown to 0x28 bytes - {u32 price; u16
    secondaryId; fieldUseFunc; description*; name[16]; ...}: "Poke Ball" at
    0x08B935E4 = item 1's name, "Great Ball" 0x28 later, item 39 = Potion
    (the user's bag).
  - gRogueItems: Rogue's own items (ids 827..1027), 0x30-byte {name[16];
    description*; u16 itemId; ...}: "Link Cable" (827) at 0x08B9DD54 with
    itemId 827 at +0x14, "Quest Book" (828) 0x30 later.
  - gRegionMapEntries: 8-byte {x, y, w, h, name*} by mapsec - the pointer to
    "Adventure" (mapsec 1) sits at 0x090BADE0. Rogue renamed Littleroot /
    Oldale / Dewford to its hub areas; the hub (mapsec 0) has no name of its
    own - the game prints SaveBlock2.pokemonHubName (see NATIVE_EMERALD_ROGUE).
  - sRegionMap_MapSectionLayout[15][28]: Emerald's grid with the hub areas'
    three cells cleared, the only copy at 0x090BA19C.
  - gMoveNames: inline 13-byte names ("Pound" at 0x084A4015 = move 1, "Tackle"
    lands at 33). gBattleMoves_Mainline: 28-byte struct BattleMove {u16 effect;
    u8 power; u8 type; ...} at 0x08BB5EA8 (Tackle 40 Normal, Ember 40 Fire, Surf
    90 Water, Earthquake 100 Ground). gBattleMoves_Revised (0x08BBC508, Rogue's
    optional Revised mode: Cut becomes 60 Grass, ...) is left out - which one a
    run uses is runtime state.
  - gSpeciesInfo types[2] at name-38 (Bulbasaur Grass/Poison, Rockruff Rock).
  - sTypeEffectivenessTable[20][20] of u32 uq4.12 at 0x08496DC4 (Gen 6+ rules).
    Type ids are vanilla's (0-17, 9 = Mystery) plus Fairy 18 and Stellar 19.
Rogue's region map is Emerald's own Hoenn art (same graphics files), so the
rects use the same MAPCURSOR (1, 2) offset as MapSecDataEmerald.kt.
"""
import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_expansion_tables import OUT_DIR, Rom, kstr, title  # noqa: E402

SHA1 = "7600af1fe08444c850c3c1227fd7dfd81336ae8e"
LABEL = "Emerald Rogue v2.2.1-EX"
ITEMS = 0x08B935E4 - 0x10 - 0x28  # gItems[0]
ITEM_STRIDE = 0x28
ROGUE_ITEMS = 0x08B9DD54  # gRogueItems[0]
ROGUE_ITEM_FIRST = 827
ROGUE_ITEM_COUNT = 201
ROGUE_ITEM_STRIDE = 0x30
MAPSECS = 0x090BADE0 - 4 - 8  # gRegionMapEntries[0]
MAPSEC_NONE = 0xD5
GRID = 0x090BA19C
GRID_W, GRID_H = 28, 15
CURSOR_X, CURSOR_Y = 1, 2  # MAPCURSOR_X_MIN / _Y_MIN
MOVE_NAMES = 0x084A4015 - 13  # gMoveNames[0]
MOVES = 0x08BB5EA8  # gBattleMoves_Mainline[0]
MOVE_STRIDE = 28
SPECIES_NAME1 = 0x0905BD04  # gSpeciesInfo[1].speciesName
SPECIES_STRIDE = 0x98
SPECIES_TYPES_OFF = -38
CHART = 0x08496DC4
TYPE_NAMES = ["Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "???",
              "Fire", "Water", "Grass", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"]


def header(what):
    return (f"package com.pokedaisy.app.companion.data\n\n"
            f"// GENERATED by scripts/gen_rogue_tables.py from the {LABEL} ROM\n"
            f"// (sha1 {SHA1[:8]}...) - do not hand-edit. {what}\n")


def write(name, body):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w") as f:
        f.write(body)
    print("wrote", os.path.relpath(path))


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <rogue.gba>")
    data = open(sys.argv[1], "rb").read()
    if hashlib.sha1(data).hexdigest() != SHA1:
        sys.exit(f"not {LABEL} (sha1 {SHA1})")
    rom = Rom(data)

    names, descs = {}, {}
    for i in range(1, ROGUE_ITEM_FIRST):
        a = ITEMS + i * ITEM_STRIDE
        n = rom.text(a + 0x10, 17)
        if not n or n.startswith("?"):
            continue
        names[i] = n
        p = rom.u32(a + 0xC)
        d = rom.text(p, 200) if rom.is_ptr(p) else None
        if d:
            descs[i] = d
    for k in range(ROGUE_ITEM_COUNT):
        a = ROGUE_ITEMS + k * ROGUE_ITEM_STRIDE
        if rom.u16(a + 0x14) != ROGUE_ITEM_FIRST + k:
            continue  # an unused slot
        n = rom.text(a, 17)
        if not n:
            continue
        names[ROGUE_ITEM_FIRST + k] = n
        p = rom.u32(a + 0x10)
        d = rom.text(p, 200) if rom.is_ptr(p) else None
        if d:
            descs[ROGUE_ITEM_FIRST + k] = d
    assert names.get(1) == "Poké Ball" and names.get(39) == "Potion", "gItems address is wrong"
    assert names.get(827) == "Link Cable" and names.get(828) == "Quest Book", "gRogueItems address is wrong"
    assert "20 points" in descs.get(39, ""), "item description offset is wrong"
    write("ItemNamesRogue.kt", header("gItems + gRogueItems (827+) names, keyed by item id.\n") +
          "val itemNamesRogue: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(names.items())) + ")\n")
    write("ItemDescriptionsRogue.kt", header("gItems + gRogueItems descriptions, keyed by item id.\n") +
          "val itemDescriptionsRogue: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(descs.items())) + ")\n")

    rows = []
    for m in range(MAPSEC_NONE):
        a = MAPSECS + 8 * m
        x, y, w, h = (rom.u8(a + k) for k in range(4))
        p = rom.u32(a + 4)
        s = rom.text(p) if rom.is_ptr(p) else None
        if m == 0:
            s = "The Pokémon Hub"  # the game prints SaveBlock2.pokemonHubName instead
        if not s:
            continue
        rows.append((m, title(s) if s.isupper() else s, x + CURSOR_X, y + CURSOR_Y, w, h))
    assert rows[1][1] == "Adventure" and rows[1][2:4] == (4 + CURSOR_X, 9 + CURSOR_Y), "gRegionMapEntries address is wrong"
    grid = data[rom.off(GRID):rom.off(GRID) + GRID_W * GRID_H]
    assert grid.count(0x10) == 1 and grid.count(0) == 0, "region map grid address is wrong"  # Route 101 once, no hub
    write("MapSecDataRogue.kt", header("gRegionMapEntries names + rects by mapsec id, on\n"
          "// Emerald's Hoenn map (regionmap/hoenn.png); x/y include MAPCURSOR (1, 2) like MapSecDataEmerald.kt.\n") +
          "val regionMapImagesRogue = arrayOf(\"hoenn\")\n\n"
          "val mapSecDataRogue: Map<Int, MapSecInfo> = mapOf(\n" +
          "".join(f"    {m} to MapSecInfo({kstr(s)}, 0, {x}, {y}, {w}, {h}),\n" for m, s, x, y, w, h in rows) + ")\n\n"
          "// sRegionMap_MapSectionLayout: the cursor grid (see RegionMapModel).\n"
          "internal val regionLayoutsRogue: List<RegionLayout> = listOf(\n"
          f"    RegionLayout({CURSOR_X}, {CURSOR_Y}, {GRID_W}, {GRID_H}, 0x{MAPSEC_NONE:02X}, listOf(hexBytes(\"{grid.hex()}\"))),\n)\n")
    moves = {}
    for m in range(1, 2000):
        n = rom.text(MOVE_NAMES + m * 13, 13)
        if not n:
            break
        a = MOVES + m * MOVE_STRIDE
        moves[m] = (n, rom.u8(a + 3), rom.u8(a + 2))
    assert moves[33] == ("Tackle", 0, 40) and moves[57] == ("Surf", 11, 90) and moves[89] == ("Earthquake", 4, 100), "move tables are wrong"
    write("MoveDataRogue.kt", header("gMoveNames + gBattleMoves_Mainline type/power (vanilla\n"
          "// type ids + Fairy 18; Rogue's Revised mode table is not used).\n") +
          "val moveDataRogue: Map<Int, MoveInfo> = mapOf(\n" +
          "".join(f"    {i} to MoveInfo({kstr(n)}, {t}, {p}),\n" for i, (n, t, p) in sorted(moves.items())) + ")\n")

    types = {}
    for sp in range(1, 3000):
        a = SPECIES_NAME1 + (sp - 1) * SPECIES_STRIDE
        if rom.off(a) + SPECIES_STRIDE > len(data):
            break
        n = rom.text(a, 13)
        if not n or n.startswith("?"):
            continue
        types[sp] = (rom.u8(a + SPECIES_TYPES_OFF), rom.u8(a + SPECIES_TYPES_OFF + 1))
    assert types[1] == (12, 3) and types[744] == (5, 5) and types[316] == (3, 3), "species types are wrong"
    write("SpeciesTypesRogue.kt", header("gSpeciesInfo types[2] by species id (National Dex), ids per typeNamesRogue.\n") +
          "val speciesTypeDataRogue: Map<Int, SpeciesTypes> = mapOf(\n" +
          "".join(f"    {i} to SpeciesTypes({a}, {b}),\n" for i, (a, b) in sorted(types.items())) + ")\n")

    chart = {}
    for atk in range(len(TYPE_NAMES)):
        for dfn in range(len(TYPE_NAMES)):
            if 9 in (atk, dfn):
                continue
            v = rom.u32(CHART + 4 * (atk * 20 + dfn))
            if v != 0x1000:
                chart[atk * 100 + dfn] = v * 100 // 0x1000
    assert chart[0 * 100 + 7] == 0 and chart[10 * 100 + 12] == 200 and 708 not in chart and chart[1618] == 0, "chart is wrong"
    write("TypeChartRogue.kt", header("Vanilla type ids plus Fairy 18. sTypeEffectivenessTable [20][20]\n"
          "// u32 uq4.12; key = atkType*100+defType -> percent, pairs not listed are 100.\n") +
          "val typeNamesRogue: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in enumerate(TYPE_NAMES)) + ")\n\n" +
          "val typeEffectivenessRogue: Map<Int, Int> = mapOf(\n" +
          "".join(f"    {k} to {v},\n" for k, v in sorted(chart.items())) + ")\n")
    print(f"{len(names)} items, {len(descs)} descriptions, {len(rows)} mapsecs, {len(moves)} moves, {len(types)} species")


if __name__ == "__main__":
    main()
