#!/usr/bin/env python3
"""Generates PokeDaisy's display tables for a Generation 1 Game Boy Pokémon game
straight from the ROM the user owns (nothing is downloaded):

    scripts/gen_gen1_tables.py yellow <rom.gb>

Writes app/src/main/kotlin/.../companion/data/{SpeciesNames,SpeciesTypes,MoveData,
ItemNames,TypeChart,MapSecData,Gen1Species}<Suffix>.kt.

Addresses (bank:address) are pret/pokeyellow's symbols: its `make` output is
byte-identical to the retail ROM (sha1 cc7d0326...), so pokeyellow.sym names
every table. Names keep the game's own ALL-CAPS casing, as the game prints them.

Gen 1 keeps its species in an internal order (RHYDON is 1) - the party / battle
structs store that index, PokedexOrder maps it to the National Dex number, and
every table here is keyed by the Dex number (the reader converts on the way in).
"""
import hashlib
import os
import struct
import sys

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "src", "main", "kotlin",
                       "com", "pokedaisy", "app", "companion", "data")

GAMES = {
    "yellow": dict(
        suffix="Yellow",
        label="Pokemon Yellow Version (USA, Europe)",
        sha1="cc7d03262ebfaf2f06772c1a480c7d9d5f4a38e1",
        monster_names=(0x3A, 0x4000), name_len=10, internal_count=190,
        pokedex_order=(0x10, 0x50B1),
        base_stats=(0x0E, 0x43DE), base_stats_size=28, dex_count=151,
        moves=(0x0E, 0x4000), move_count=165, move_names=(0x2F, 0x4000),
        item_names=(0x01, 0x45B7), item_count=0x61,
        tm_moves=(0x04, 0x632D),   # TechnicalMachines: TM01-50 then HM01-05, a move id each
        type_names=(0x09, 0x7D63), type_count=0x1B,
        type_effects=(0x0F, 0x65FA),
        external_maps=(0x1C, 0x539C), internal_maps=(0x1C, 0x540B), first_indoor_map=0x25, map_count=0xF8,
        checks=dict(species={1: "BULBASAUR", 25: "PIKACHU", 150: "MEWTWO", 151: "MEW"},
                    types={1: (0x16, 0x03), 25: (0x17, 0x17), 81: (0x17, 0x17), 35: (0x00, 0x00)},
                    moves={1: ("POUND", 0, 40), 44: ("BITE", 0, 60), 16: ("GUST", 0, 40), 85: ("THUNDERBOLT", 0x17, 95)},
                    items={1: "MASTER BALL", 4: "POKé BALL", 20: "POTION", 0xC9: "TM01", 0xC4: "HM01"},
                    maps={0: "PALLET TOWN", 1: "VIRIDIAN CITY", 0x0C: "ROUTE 1"}),
    ),
}

CHARS = {0x7F: " ", 0xBA: "é", 0xE0: "'", 0xE3: "-", 0xE6: "?", 0xE7: "!", 0xE8: ".", 0xEF: "♂", 0xF5: "♀",
         0xF3: "/", 0xF4: ",", 0x9A: "(", 0x9B: ")", 0x9C: ":", 0x9D: ";", 0x9E: "[", 0x9F: "]", 0xF2: ".",
         0x54: "POKé", 0x4A: "PKMN", 0xE1: "PK", 0xE2: "MN", 0xBB: "'d", 0xBC: "'l", 0xBD: "'s", 0xBE: "'t",
         0xBF: "'v", 0xE4: "'r", 0xE5: "'m", 0x75: "…", 0xF1: "×", 0x4E: " ", 0x4F: " "}
CHARS.update({0x80 + i: chr(65 + i) for i in range(26)})
CHARS.update({0xA0 + i: chr(97 + i) for i in range(26)})
CHARS.update({0xF6 + i: str(i) for i in range(10)})


class Rom:
    def __init__(self, data):
        self.d = data

    @staticmethod
    def off(bank, addr):
        return addr if bank == 0 else bank * 0x4000 + (addr - 0x4000)

    def u8(self, bank, addr):
        return self.d[self.off(bank, addr)]

    def text(self, bank, addr, maxlen=40):
        out = []
        o = self.off(bank, addr)
        for b in self.d[o:o + maxlen]:
            if b == 0x50:
                return "".join(out)
            if b not in CHARS:
                raise ValueError(f"unknown char {b:02X} at {bank:02X}:{addr:04X}")
            out.append(CHARS[b])
        raise ValueError(f"unterminated text at {bank:02X}:{addr:04X}")

    def text_list(self, bank, addr, count):
        """`count` 0x50-terminated strings back to back (MoveNames, ItemNames)."""
        out = []
        for _ in range(count):
            s = self.text(bank, addr)
            out.append(s)
            o = self.off(bank, addr)
            addr += self.d.index(0x50, o) - o + 1
        return out


def kstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write(name, header, body):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w") as f:
        f.write("package com.pokedaisy.app.companion.data\n\n" + header + "\n" + body)
    print("wrote", os.path.relpath(path))


def kmap(name, typ, items):
    lines = [f"val {name}: Map<Int, {typ}> = mapOf("]
    lines += [f"    {k} to {v}," for k, v in items]
    return "\n".join(lines) + "\n)\n"


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in GAMES:
        sys.exit(f"usage: {sys.argv[0]} <{'|'.join(GAMES)}> <rom.gb>")
    g = GAMES[sys.argv[1]]
    data = open(sys.argv[2], "rb").read()
    if hashlib.sha1(data).hexdigest() != g["sha1"]:
        sys.exit(f"{sys.argv[2]} isn't {g['label']} (sha1 {g['sha1'][:8]}...)")
    rom = Rom(data)
    sfx, c = g["suffix"], g["checks"]
    head = (f"// GENERATED by scripts/gen_gen1_tables.py from the {g['label']} ROM\n"
            f"// (sha1 {g['sha1'][:8]}...) - do not hand-edit.")

    # Species: internal index -> Dex number, names by internal index, base stats by Dex number.
    ob, oa = g["pokedex_order"]
    internal_to_dex = [0] + [rom.u8(ob, oa + i) for i in range(g["internal_count"])]
    mb, ma = g["monster_names"]
    names = {}
    for idx in range(1, g["internal_count"] + 1):
        dex = internal_to_dex[idx]
        if dex == 0:
            continue  # MISSINGNO. slots
        raw = data[rom.off(mb, ma + (idx - 1) * g["name_len"]):][:g["name_len"]]
        names[dex] = "".join(CHARS[b] for b in raw.split(b"\x50")[0])
    bb, ba = g["base_stats"]
    types = {}
    for dex in range(1, g["dex_count"] + 1):
        o = rom.off(bb, ba + (dex - 1) * g["base_stats_size"])
        assert data[o] == dex, f"base stats {dex}: dex id {data[o]}"
        types[dex] = (data[o + 6], data[o + 7])
    assert all(names[k] == v for k, v in c["species"].items()), "species names"
    assert all(types[k] == v for k, v in c["types"].items()), "species types"

    # Moves: 6-byte entries (animation, effect, power, type, accuracy, pp) + MoveNames.
    nb, na = g["move_names"]
    move_names = rom.text_list(nb, na, g["move_count"])
    mvb, mva = g["moves"]
    moves = {}
    for i in range(g["move_count"]):
        o = rom.off(mvb, mva + i * 6)
        assert data[o] == i + 1, f"move {i + 1}: animation {data[o]}"
        moves[i + 1] = (move_names[i], data[o + 3], data[o + 2])
    assert all(moves[k] == v for k, v in c["moves"].items()), "moves"

    # Items: ItemNames for 1..item_count; HM01-05 (0xC4-0xC8) and TM01-50 (0xC9-0xFA)
    # are named by the game's own code, the way it prints them.
    ib, ia = g["item_names"]
    items = {i + 1: n for i, n in enumerate(rom.text_list(ib, ia, g["item_count"]))}
    items.update({0xC4 + i: f"HM{i + 1:02d}" for i in range(5)})
    items.update({0xC9 + i: f"TM{i + 1:02d}" for i in range(50)})
    assert all(items[k] == v for k, v in c["items"].items()), "items"

    # Types: a pointer table (the unused ids point at NORMAL - left out) + TypeEffects
    # (attacker, defender, x10 multiplier; 0xFF ends it).
    tb, ta = g["type_names"]
    type_names = {}
    for t in range(g["type_count"]):
        p = struct.unpack_from("<H", data, rom.off(tb, ta + 2 * t))[0]
        n = rom.text(tb, p)
        if n == "NORMAL" and t != 0:
            continue
        type_names[t] = n
    eb, ea = g["type_effects"]
    chart = {}
    o = rom.off(eb, ea)
    while data[o] != 0xFF:
        atk, dfn, mult = data[o], data[o + 1], data[o + 2]
        chart[atk * 100 + dfn] = mult * 10
        o += 3

    # Map names + town-map tiles: ExternalMapEntries (outdoor maps, 3 bytes: yx nibbles,
    # name pointer) and InternalMapEntries (4 bytes: last map id + 1 of the group, yx, name).
    xb, xa = g["external_maps"]
    ib2, ia2 = g["internal_maps"]
    internal = []
    o = rom.off(ib2, ia2)
    while data[o] != 0xFF:
        internal.append((data[o], data[o + 1], struct.unpack_from("<H", data, o + 2)[0]))
        o += 4
    maps = {}
    for m in range(g["map_count"]):
        if m < g["first_indoor_map"]:
            o = rom.off(xb, xa + 3 * m)
            yx, p = data[o], struct.unpack_from("<H", data, o + 1)[0]
        else:
            entry = next((e for e in internal if m < e[0]), None)
            if entry is None:
                continue
            yx, p = entry[1], entry[2]
        maps[m] = (rom.text(xb, p), yx & 0xF, yx >> 4)
    assert all(maps[k][0] == v for k, v in c["maps"].items()), "maps"

    # TMs / HMs: Gen 1 gives items no description text; the TM's own move says what it does.
    tb2, ta2 = g["tm_moves"]
    tm = {}
    for i in range(55):
        mv = data[rom.off(tb2, ta2 + i)]
        item = 0xC9 + i if i < 50 else 0xC4 + (i - 50)
        tm[item] = f"Teaches {moves[mv][0]} to a POKéMON." + (" Can be used again." if i >= 50 else "")
    write(f"ItemDescriptionsTm{sfx}.kt", head + " TechnicalMachines: what each TM / HM teaches\n"
          "// (the game has no item descriptions; ItemDescriptionsYellow.kt has the rest, hand-written).\n",
          kmap(f"tmDescriptions{sfx}", "String", [(k, kstr(v)) for k, v in sorted(tm.items())]))

    write(f"Gen1Species{sfx}.kt", head + " PokedexOrder: the party / battle structs'\n"
          "// internal species index -> National Dex number (0 = MISSINGNO.).\n",
          f"val gen1InternalToDex{sfx} = intArrayOf(\n" +
          "".join(f"    {d},\n" for d in internal_to_dex) + ")\n")
    write(f"SpeciesNames{sfx}.kt", head + " MonsterNames, keyed by National Dex number.\n",
          kmap(f"speciesNames{sfx}", "String", [(k, kstr(names[k])) for k in sorted(names)]))
    write(f"SpeciesTypes{sfx}.kt", head + f" BaseStats types, ids per typeNames{sfx}.\n",
          kmap(f"speciesTypeData{sfx}", "SpeciesTypes", [(k, f"SpeciesTypes({a}, {b})") for k, (a, b) in sorted(types.items())]))
    write(f"MoveData{sfx}.kt", head + " MoveNames + Moves (type, power).\n",
          kmap(f"moveData{sfx}", "MoveInfo", [(k, f"MoveInfo({kstr(n)}, {t}, {p})") for k, (n, t, p) in sorted(moves.items())]))
    write(f"ItemNames{sfx}.kt", head + " ItemNames, plus the HMs / TMs the game names in code.\n",
          kmap(f"itemNames{sfx}", "String", [(k, kstr(v)) for k, v in sorted(items.items())]))
    write(f"TypeChart{sfx}.kt", head + " TypeNames (Gen 1 ids: 0-8 Normal..Ghost,\n"
          "// 20-26 Fire..Dragon) and TypeEffects: key = atkType*100+defType -> percent, pairs not\n"
          "// listed are 100. Gen 1's own chart, Ghost -> Psychic 0x included.\n",
          kmap(f"typeNames{sfx}", "String", [(k, kstr(v)) for k, v in sorted(type_names.items())]) + "\n" +
          kmap(f"typeEffectiveness{sfx}", "Int", sorted(chart.items())))
    # A town-map coordinate is where the game puts the player's 16x16 head (OAM (x*8+24, y*8+24),
    # TownMapCoordsToOAMCoords): its top-left 8px cell, i.e. the place's own square, is (x+2, y+1).
    write(f"MapSecData{sfx}.kt", head + " Map names by map id (wCurMap), from the town\n"
          "// map's ExternalMapEntries / InternalMapEntries; x / y = the place's 8px cell on the town map\n"
          "// (regionmap/yellow.png, which Gen1Art rebuilds from the ROM).\n",
          kmap(f"mapSecData{sfx}", "MapSecInfo", [(k, f"MapSecInfo({kstr(n)}, 0, {x + 2}, {y + 1}, 1, 1)") for k, (n, x, y) in sorted(maps.items())]))
    print(f"{len(names)} species, {len(moves)} moves, {len(items)} items, {len(type_names)} types, {len(maps)} maps")


if __name__ == "__main__":
    main()
