#!/usr/bin/env python3
"""Generates Pokémon Orange Islands' display tables from the ROM the user owns
(a 16 MB binary hack of FireRed 1.0, BPRE rev 0, no source; nothing is
downloaded).

    scripts/gen_orange_islands_tables.py <rom.gba>

Writes {SpeciesNames,SpeciesTypes,GenderRatios,MoveData,ItemNames,TypeChart,
MapSecData}OrangeIslands.kt into the app's data package. Item descriptions
aren't written: the app reads them from the player's ROM (RomItemText,
NativeConfig.itemDescs = gItems below).

Orange Islands keeps FireRed 1.0's code, RAM and table shapes - most tables
sit at retail rev 0's own addresses, edited in place (checked against a retail
rev 0 ROM, sha1 41cb23d8...): gSpeciesNames 0x08245EE0 (species 409 is a
CRYSTAL ONIX now, the starters / PIKACHU have new base stats), gMoveNames
0x08247094 + gBattleMoves 0x08250C04 (353 / 354 are CRYSTALTHROW / CRYSTALSLIDE),
gBaseStats 0x08254784 (28 bytes: types +6 / +7, genderRatio +0x10), gItems
0x083DB028 (renamed key items: ORANGE PASS, SHOWBOAT PASS, GS BALL, ...).
Two were repointed (the literal-pool words FireRed loads them from): gTypeNames
0x088862C0 (7-byte names, a 24th type CRYSTL at id 23) and gTypeEffectiveness
0x08886140 ({atk, def, x10} triplets, 0xFE before the Foresight-ignored ones,
0xFF at the end). Map section names: sMapNames 0x083F1CAC (pointers from MAPSEC
0x58; its own Orange Archipelago), title-cased like RomRegionMap, which also
draws its region map from the ROM. Names keep the ROM's capitals, like FireRed.
"""
import hashlib
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_emerald_lang_tables import CHARS  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "src", "main", "kotlin",
                       "com", "pokedaisy", "app", "companion", "data")
SHA1 = "8bac897de515f88e6ce92d0712ce2c018a394b37"
# Beta 5.7: the same tables (its ROM differs from the release in 80 bytes of map text and data).
BETA_SHA1 = "d2e3800e69e44c9649c3d9a15dc1cd12c1d90501"
LABEL = "Pokemon Orange Islands"
B = 0x08000000
SPECIES_NAMES, SPECIES_COUNT = 0x08245EE0, 412
BASE_STATS = 0x08254784
MOVE_NAMES, BATTLE_MOVES, MOVES_COUNT = 0x08247094, 0x08250C04, 355
ITEMS, ITEMS_COUNT = 0x083DB028, 375
TYPE_NAMES, TYPE_CHART, TYPE_COUNT = 0x088862C0, 0x08886140, 24
MAP_NAMES, FIRST_MAPSEC, SECTIONS = 0x083F1CAC, 0x58, 109
# The app's type names (colours are keyed by them): vanilla's, and CRYSTL as Crystal.
TYPE_NAMES_APP = {0: "Normal", 1: "Fighting", 2: "Flying", 3: "Poison", 4: "Ground", 5: "Rock", 6: "Bug",
                  7: "Ghost", 8: "Steel", 9: "???", 10: "Fire", 11: "Water", 12: "Grass", 13: "Electric",
                  14: "Psychic", 15: "Ice", 16: "Dragon", 17: "Dark", 23: "Crystal"}
CH = dict(CHARS)


def text(d, a, maxlen):
    out = []
    for b in d[a - B:a - B + maxlen]:
        if b == 0xFF:
            break
        if b in (0xFA, 0xFB, 0xFE):
            out.append(" ")
            continue
        if b not in CH:
            return None
        out.append(CH[b])
    s = " ".join("".join(out).split())
    return s if s and set(s) != {"?"} else None


def u8(d, a):
    return d[a - B]


def u16(d, a):
    return struct.unpack_from("<H", d, a - B)[0]


def u32(d, a):
    return struct.unpack_from("<I", d, a - B)[0]


def kstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def title_case(s):
    """RomRegionMap.titleCase: ALL-CAPS names in title case, others as they are."""
    if any("a" <= c <= "z" for c in s):
        return s
    out, start = [], True
    for c in s:
        out.append(c.upper() if start else c.lower())
        start = not c.isalpha() and c != "’"
    return "".join(out)


def header(what):
    return (f"package com.pokedaisy.app.companion.data\n\n"
            f"// GENERATED by scripts/gen_orange_islands_tables.py from the {LABEL} ROM\n"
            f"// (sha1 {SHA1[:8]}...) - do not hand-edit. {what}\n")


def write(name, body):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print("wrote", os.path.relpath(path))


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <rom.gba>")
    d = open(sys.argv[1], "rb").read()
    if hashlib.sha1(d).hexdigest() not in (SHA1, BETA_SHA1):
        sys.exit(f"not {LABEL} (sha1 {SHA1} or {BETA_SHA1})")

    names, types, gender = {}, {}, {}
    for i in range(1, SPECIES_COUNT):
        n = text(d, SPECIES_NAMES + 11 * i, 11)
        if not n:
            continue
        names[i] = n
        b = BASE_STATS + 28 * i
        types[i] = (u8(d, b + 6), u8(d, b + 7))
        gender[i] = u8(d, b + 0x10)
    assert names[25] == "PIKACHU" and names[409] == "ONIX" and types[409] == (23, 4) and types[1] == (12, 3)
    write("SpeciesNamesOrangeIslands.kt", header("gSpeciesNames, FireRed's species ids (409: its\n"
          "// CRYSTAL ONIX, in Jirachi's slot).\n") +
          "val speciesNamesOrangeIslands: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(names.items())) + ")\n")
    write("SpeciesTypesOrangeIslands.kt", header("gBaseStats types (FireRed's ids, CRYSTL 23).\n") +
          "val speciesTypeDataOrangeIslands: Map<Int, SpeciesTypes> = mapOf(\n" +
          "".join(f"    {i} to SpeciesTypes({a}, {b}),\n" for i, (a, b) in sorted(types.items())) + ")\n")
    hexs = "".join("%02x" % gender.get(i, 255) for i in range(SPECIES_COUNT))
    write("GenderRatiosOrangeIslands.kt", header("gBaseStats genderRatio by species id (0 always\n"
          "// male, 254 always female, 255 genderless, else female when (personality & 0xFF) < ratio).\n") +
          f"val genderRatiosOrangeIslands: IntArray by lazy {{ unhexRatios(\"{hexs}\") }}\n")

    moves = {}
    for i in range(1, MOVES_COUNT):
        n = text(d, MOVE_NAMES + 13 * i, 13)
        if n:
            a = BATTLE_MOVES + 12 * i
            moves[i] = (n, u8(d, a + 2), u8(d, a + 1))
    assert moves[33] == ("TACKLE", 0, 40) and moves[84][0] == "THUNDERSHOCK" and moves[353] == ("CRYSTALTHROW", 23, 50)
    write("MoveDataOrangeIslands.kt", header("gMoveNames + gBattleMoves type / power.\n") +
          "val moveDataOrangeIslands: Map<Int, MoveInfo> = mapOf(\n" +
          "".join(f"    {i} to MoveInfo({kstr(n)}, {t}, {p}),\n" for i, (n, t, p) in sorted(moves.items())) + ")\n")

    items = {}
    for slot in range(1, ITEMS_COUNT):
        a = ITEMS + 44 * slot
        n, iid = text(d, a, 14), u16(d, a + 14)
        if n and iid == slot:
            items[iid] = n
    assert items[13] == "POTION" and items[266] == "ORANGE PASS" and items[270] == "GS BALL"
    write("ItemNamesOrangeIslands.kt", header("gItems names by item id.\n") +
          "val itemNamesOrangeIslands: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(items.items())) + ")\n")

    rom_types = {i: text(d, TYPE_NAMES + 7 * i, 7) for i in range(TYPE_COUNT)}
    assert rom_types[23] == "CRYSTL" and rom_types[10] == "FIRE"
    chart, a = {}, TYPE_CHART
    while u8(d, a) != 0xFF:
        atk, dfn, x = u8(d, a), u8(d, a + 1), u8(d, a + 2)
        a += 3
        if atk == 0xFE:  # the Foresight separator
            continue
        chart[atk * 100 + dfn] = x * 10
    assert chart[7] == 0 and chart[1012] == 200 and chart[2306] == 200 and chart[1123] == 0
    write("TypeChartOrangeIslands.kt", header("gTypeNames (repointed: CRYSTL is type 23, here\n"
          "// \"Crystal\") and gTypeEffectiveness (repointed, its Crystal rows added); key =\n"
          "// atkType*100+defType -> percent, pairs not listed are 100.\n") +
          "val typeNamesOrangeIslands: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(TYPE_NAMES_APP.items())) + ")\n\n" +
          "val typeEffectivenessOrangeIslands: Map<Int, Int> = mapOf(\n" +
          "".join(f"    {k} to {v},\n" for k, v in chart.items()) + ")\n")

    secs = {}
    for i in range(SECTIONS):
        p = u32(d, MAP_NAMES + 4 * i)
        n = text(d, p, 32) if B <= p < B + len(d) else None
        if n:
            secs[FIRST_MAPSEC + i] = title_case(n)
    assert secs[0x65] == "Valencia Island"
    write("MapSecDataOrangeIslands.kt", header("sMapNames by map section id, region -1: the MAP\n"
          "// draws its region map and boxes from the ROM (RomRegionMap); these name it elsewhere.\n") +
          "val mapSecDataOrangeIslands: Map<Int, MapSecInfo> = mapOf(\n" +
          "".join(f"    {i} to MapSecInfo({kstr(n)}, -1, 0, 0, 0, 0),\n" for i, n in sorted(secs.items())) + ")\n")
    print(f"{len(names)} species, {len(moves)} moves, {len(items)} items, {len(chart)} chart pairs, {len(secs)} map sections")


if __name__ == "__main__":
    main()
