#!/usr/bin/env python3
"""Generate item names + descriptions exactly as FireRed / Emerald print them
in the bag ("POKé BALL", "PARLYZ HEAL", "...heals one POKéMON...") for
PokeDaisy's Items tab.

The shared itemNames / itemDescriptions tables (ItemNames.kt,
ItemDescriptions.kt) are an app-wide Title Case spelling ("Paralyze Heal",
"Pokemon") taken from FireRed only; the Items tab mimics the game's own bag
screen, so it shows each game's own strings instead (Emerald's descriptions
are different text from FireRed's, not just different casing).

Emits (into app/src/main/kotlin/.../companion/data/):
  - ItemTextGame.kt  (itemNames/ItemDescriptions x FireRed/Emerald "Game" maps)

Source of truth: pokefirered + pokeemerald checkouts at the pinned commits (see
this repo's root CLAUDE.md). Dev-time generator, not wired into build.sh -
re-run only if a pinned decomp commit changes.

Usage:
  python3 scripts/gen_item_game_text.py /path/to/pokefirered /path/to/pokeemerald
"""
import json
import os
import re
import sys

OUT = os.path.join(
    os.path.dirname(__file__),
    "../app/src/main/kotlin/com/pokedaisy/app/companion/data/ItemTextGame.kt",
)
UNUSED = "????????"
# charmap.txt control codes that show up in item text -> what the game draws
# (POKEBLOCK is a 5-tile ligature spelling "POKéBLOCK").
CHARMAP_MACROS = {"{POKEBLOCK}": "POKéBLOCK", "{PKMN}": "PKMN"}


def firered_text(decomp: str) -> tuple[dict[int, str], dict[int, str]]:
    """pokefirered keeps gItems as JSON, one entry per item id in order."""
    data = json.load(open(os.path.join(decomp, "src/data/items.json")))
    items = data["items"] if isinstance(data, dict) else data
    names = {i: it["english"] for i, it in enumerate(items)}
    descs = {i: it["description_english"].replace("\\n", " ") for i, it in enumerate(items)}
    return names, descs


def emerald_text(decomp: str) -> tuple[dict[int, str], dict[int, str]]:
    """pokeemerald keeps gItems as a C initializer, descriptions as u8 arrays."""
    # Item ids are a plain sequential enum (no explicit values) at this pin.
    header = open(os.path.join(decomp, "include/constants/items.h")).read()
    body = re.sub(r"//[^\n]*", "", header[header.index("enum {"):header.index("};")])
    constants = re.findall(r"\b(ITEM_[A-Z0-9_]+)\s*,", body)
    assert "=" not in body, "items enum has explicit values - update this parser"
    ids = {c: i for i, c in enumerate(constants)}

    desc_src = open(os.path.join(decomp, "src/data/text/item_descriptions.h")).read()
    desc_text = {
        m.group(1): " ".join(re.findall(r'"([^"]*)"', m.group(2))).replace("\\n", " ")
        for m in re.finditer(r"static const u8 (\w+)\[\]\s*=\s*_\((.*?)\);", desc_src, re.S)
    }

    src = open(os.path.join(decomp, "src/data/items.h")).read()
    names, descs = {}, {}
    # Keyed by each entry's .itemId, not its [designator] - TMs use aliases
    # there (ITEM_TM_FOCUS_PUNCH) that aren't in the enum.
    for m in re.finditer(
        r"\.name\s*=\s*_\(\"([^\"]*)\"\),\s*\.itemId\s*=\s*(ITEM_[A-Z0-9_]+),.*?\.description\s*=\s*(\w+)",
        src, re.S,
    ):
        item = ids[m.group(2)]
        names[item] = m.group(1)
        descs[item] = desc_text[m.group(3)]
    return names, descs


def expand(s: str) -> str:
    for macro, text in CHARMAP_MACROS.items():
        s = s.replace(macro, text)
    s = re.sub(r"\s+", " ", s).strip()
    assert not re.search(r'[{}$"\\]', s), f"unhandled control code in item text: {s!r}"
    return s


def emit(name: str, table: dict[int, str], names: dict[int, str]) -> str:
    rows = [
        f'    {i} to "{expand(s)}",'
        for i, s in sorted(table.items())
        if i != 0 and names.get(i) != UNUSED and s
    ]
    return f"val {name}: Map<Int, String> = mapOf(\n" + "\n".join(rows) + "\n)\n"


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    fr_names, fr_descs = firered_text(sys.argv[1])
    em_names, em_descs = emerald_text(sys.argv[2])
    assert fr_names[4] == "POKé BALL" and em_names[4] == "POKé BALL", "unexpected item table layout"
    assert "POKéMON" in fr_descs[18] and "POKéMON" in em_descs[18], "unexpected description layout"
    with open(OUT, "w") as f:
        f.write(
            "package com.pokedaisy.app.companion.data\n\n"
            "// GENERATED by scripts/gen_item_game_text.py from the pinned pokefirered /\n"
            "// pokeemerald checkouts - item names + descriptions exactly as each game's\n"
            "// bag prints them (line breaks joined). Regenerate rather than hand-edit.\n\n"
            + emit("itemNamesFireRedGame", fr_names, fr_names) + "\n"
            + emit("itemNamesEmeraldGame", em_names, em_names) + "\n"
            + emit("itemDescriptionsFireRedGame", fr_descs, fr_names) + "\n"
            + emit("itemDescriptionsEmeraldGame", em_descs, em_names)
        )
    print(f"wrote {OUT}: {len(fr_names)} FireRed, {len(em_names)} Emerald items")


if __name__ == "__main__":
    main()
