#!/usr/bin/env python3
"""Generates PokeDaisy's display tables for a CFRU-based FireRed hack (a
binary hack on FireRed 1.0 with no source), straight from the ROM the user
owns (nothing is downloaded).

    scripts/gen_cfru_tables.py <game-key> <rom.gba>

Writes app/src/main/kotlin/.../companion/data/{SpeciesNames,SpeciesTypes,
MoveData,ItemNames}<Suffix>.kt. Item descriptions aren't written: the app reads
them from the player's ROM (RomItemText, NativeConfig.itemDescs = gItems below).

CFRU keeps FireRed's code and repoints its data, so each table is found the
way NATIVE_GAIA_V3_2's icon tables were: the literal-pool words FireRed 1.0
loads gSpeciesNames, gMonIconTable, ... from now hold the hack's addresses
(compare a retail BPRE rev 0 ROM word for word). The shapes:
  - gSpeciesNames: 11-byte names, by the hack's own species ids.
  - gBaseStats: 28-byte records, type1/type2 at +6/+7 (CFRU type ids, Fairy 23).
  - move names: CFRU's 17-byte long names (gMoveNames' 13 truncate
    "Thunder Punch" to "ThunderPunch"); gBattleMoves: 12-byte records, power
    at +1, type at +2.
  - gItems: 44-byte struct Item, name inline (14), .itemId at +14 (the key:
    it can differ from the slot), description pointer at +20.
The sha1 check stops a table being generated from the wrong release.
"""
import hashlib
import os
import struct
import sys

from gen_expansion_tables import OUT_DIR, Rom, kstr

GAMES = {
    # Pokemon Radical Red v4.1. FireRed 1.0's literal pools say: gSpeciesNames
    # 0x094042CC (pool 0x08000144 and 39 more), gMonIconTable 0x097FE6CC,
    # gMonIconPaletteIndices 0x097FE164, sItemIconTable 0x093C8100 (those last
    # three are NATIVE_RADICAL_RED_V4_1's). gBaseStats / gItems / the move
    # tables by shape, each the copy the code references (vanilla's are still
    # in the ROM, unreferenced). Checked against a save's party (species 1331
    # Maushold knows Super Fang, 925 Crocalor Yawn, 844 Pawmo Arm Thrust) and
    # bag (58 Muscle Wing, 675 Wise Glasses, 747 Punch Glove). Moves end at
    # 1003 (Rapid Flow); past that the long-name stride runs into other text.
    "radical_red": dict(
        suffix="RadicalRed",
        label="Pokemon Radical Red v4.1",
        sha1="964f951a0fdaf209e4ea1344883ef0d557bb3a80",
        species_names=0x094042CC, species_max=1400,
        base_stats=0x097B98EC,
        move_names=0x090EEEDC, move_name_len=17, battle_moves=0x091521D0, moves_max=1003,
        items=0x093C0000, items_max=2000,
        checks=dict(species={1: "Bulbasaur", 25: "Pikachu", 277: "Treecko", 925: "Crocalor", 1331: "Maushold"},
                    types={1: (12, 3), 4: (10, 10), 35: (23, 23)},
                    moves={33: ("Tackle", 0, 40), 7: ("Fire Punch", 10, 75), 474: ("Incinerate", 10, 60),
                           825: ("Alluring Voice", 23, 80)},
                    items={1: "Master Ball", 13: "Potion", 58: "Muscle Wing", 675: "Wise Glasses", 747: "Punch Glove"}),
    ),
}


def header(g, what):
    return (f"package com.pokedaisy.app.companion.data\n\n"
            f"// GENERATED by scripts/gen_cfru_tables.py from the {g['label']} ROM\n"
            f"// (sha1 {g['sha1'][:8]}...) - do not hand-edit. {what}\n")


def write(name, body):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w") as f:
        f.write(body)
    print("wrote", os.path.relpath(path))


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in GAMES:
        sys.exit(f"usage: {sys.argv[0]} <{'|'.join(GAMES)}> <rom.gba>")
    g = GAMES[sys.argv[1]]
    data = open(sys.argv[2], "rb").read()
    sha1 = hashlib.sha1(data).hexdigest()
    if sha1 != g["sha1"]:
        sys.exit(f"sha1 {sha1} isn't {g['label']}'s {g['sha1']}")
    rom = Rom(data)
    sfx = g["suffix"]
    checks = g["checks"]

    # Species: unused slots are "?" - skip them, not stop.
    names = {}
    for i in range(1, g["species_max"]):
        n = rom.text(g["species_names"] + 11 * i, 11)
        if n and not n.startswith("?"):
            names[i] = n
    for i, n in checks["species"].items():
        assert names.get(i) == n, (i, names.get(i), n)
    types = {i: (rom.u8(g["base_stats"] + 28 * i + 6), rom.u8(g["base_stats"] + 28 * i + 7)) for i in names}
    for i, t in checks["types"].items():
        assert types[i] == t, (i, types[i], t)
    write(f"SpeciesNames{sfx}.kt", header(g, "gSpeciesNames by the hack's own species ids.\n") +
          f"val speciesNames{sfx}: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(names.items())) + ")\n")
    write(f"SpeciesTypes{sfx}.kt", header(g, "gBaseStats type1/type2, CFRU type ids (Fairy 23).\n") +
          f"val speciesTypeData{sfx}: Map<Int, SpeciesTypes> = mapOf(\n" +
          "".join(f"    {i} to SpeciesTypes({a}, {b}),\n" for i, (a, b) in sorted(types.items())) + ")\n")

    moves = {}
    for i in range(1, g["moves_max"] + 1):
        n = rom.text(g["move_names"] + g["move_name_len"] * i, g["move_name_len"])
        if not n or n == "Placeholder" or n.startswith("Z-Move"):
            continue
        a = g["battle_moves"] + 12 * i
        moves[i] = (n, rom.u8(a + 2), rom.u8(a + 1))
    for i, m in checks["moves"].items():
        assert moves.get(i) == m, (i, moves.get(i), m)
    write(f"MoveData{sfx}.kt", header(g, "Long move names + gBattleMoves type/power.\n") +
          f"val moveData{sfx}: Map<Int, MoveInfo> = mapOf(\n" +
          "".join(f"    {i} to MoveInfo({kstr(n)}, {t}, {p}),\n" for i, (n, t, p) in sorted(moves.items())) + ")\n")

    # The array ends where 30 slots in a row aren't items.
    items = {}
    misses = 0
    for slot in range(1, g["items_max"]):
        a = g["items"] + 44 * slot
        if rom.off(a) + 44 > len(data) or misses >= 30:
            break
        iid = rom.u16(a + 14)
        n = rom.text(a, 14)
        if not n or not 0 < iid < 4000 or iid in items:
            misses += 1
            continue
        misses = 0
        if n.startswith("?"):
            continue
        items[iid] = n
    for i, n in checks["items"].items():
        assert items.get(i) == n, (i, items.get(i), n)
    write(f"ItemNames{sfx}.kt", header(g, "gItems names, keyed by .itemId.\n") +
          f"val itemNames{sfx}: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(items.items())) + ")\n")
    print(f"{len(names)} species, {len(moves)} moves, {len(items)} items; itemDescs = vanillaItems(0x{g['items']:08X}L)")


if __name__ == "__main__":
    main()
