// The PokeDaisy mark in the app, from the website's own drawing (website/src/lib/pixel.js, daisyBall):
//  - app/src/main/kotlin/.../companion/ui/LogoGen.kt: the website's mark as it is - its rows and palette,
//    for PixelArt (the Library's title, the PokéDaisy theme's backdrop).
//  - app/src/main/res/mipmap-*/ic_launcher_foreground.png: the launcher icon's foreground - the mark with
//    the icon's two edits ([iconLogo]: the 3 and 9 o'clock petal tips rounded, a 2 px outline) at a whole
//    scale inside the adaptive icon's safe zone, over the blue ic_launcher_background.
//
//     node scripts/gen_logo.mjs
import { writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SPRITES } from '../website/src/lib/pixel.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** The side (3 and 9 o'clock) petals' tips rounded: the band's notch at each tip filled in. */
function roundSideTips(rows) {
  const g = rows.map((r) => [...r]);
  const n = g.length;
  for (const col of [0, n - 1]) {
    const inked = g.map((r, y) => (r[col] !== '.' ? y : -1)).filter((y) => y >= 0);
    for (let y = Math.min(...inked); y <= Math.max(...inked); y++) if (g[y][col] === '.') g[y][col] = 'K';
  }
  return g.map((r) => r.join(''));
}

/** One more pixel of outline all round the outside (4-neighbour, so corners stay round): the grid grows by
 * 2, the flower inside stays pixel for pixel. */
function thickenOutline(rows) {
  const w = rows[0].length + 2;
  const g = ['.'.repeat(w), ...rows.map((r) => `.${r}.`), '.'.repeat(w)].map((r) => [...r]);
  const ink = (x, y) => g[y]?.[x] !== undefined && g[y][x] !== '.';
  const out = g.map((r, y) => r.map((c, x) =>
    c === '.' && [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dy]) => ink(x + dx, y + dy)) ? 'K' : c));
  return out.map((r) => r.join(''));
}

const logo = SPRITES.logo;
const iconLogo = { pal: logo.pal, rows: thickenOutline(roundSideTips(logo.rows)) };

// --- Kotlin ------------------------------------------------------------------------------------
const pal = Object.entries(logo.pal)
  .map(([k, v]) => `    '${k}' to Color(0xFF${v.slice(1).toUpperCase()}),`)
  .join('\n');
const rows = logo.rows.map((r) => `    "${r}",`).join('\n');
writeFileSync(
  join(root, 'app/src/main/kotlin/com/pokedaisy/app/companion/ui/LogoGen.kt'),
  `// Generated by scripts/gen_logo.mjs from website/src/lib/pixel.js - don't edit by hand.
package com.pokedaisy.app.companion.ui

import androidx.compose.ui.graphics.Color

/** The PokeDaisy mark (a daisy drawn as a Poké Ball), for [PixelArt] with [LOGO_PALETTE]. */
val LOGO_ROWS = listOf(
${rows}
)

val LOGO_PALETTE = mapOf(
${pal}
)
`,
);

// --- launcher PNGs -----------------------------------------------------------------------------
// Adaptive icons: a 108 dp canvas, of which the middle 66 dp circle always shows.
const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
/** How wide the mark is on the icon, of its 108 dp (Android's keylines put an icon's art at ~48 dp): picked by eye. */
const ICON_DP = 51;
const crcTable = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
const crc32 = (buf) => {
  let c = 0xffffffff;
  for (const b of buf) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
};
const chunk = (type, data) => {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(td));
  return Buffer.concat([len, td, crc]);
};
function png(size, pixel) {
  const raw = Buffer.alloc(size * (size * 4 + 1));
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0;
    for (let x = 0; x < size; x++) {
      const [r, g, b, a] = pixel(x, y);
      const o = y * (size * 4 + 1) + 1 + x * 4;
      raw[o] = r; raw[o + 1] = g; raw[o + 2] = b; raw[o + 3] = a;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; ihdr[9] = 6; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr), chunk('IDAT', deflateSync(raw)), chunk('IEND', Buffer.alloc(0)),
  ]);
}
const n = iconLogo.rows.length;
for (const [name, d] of Object.entries(DENSITIES)) {
  const size = Math.round(108 * d);
  // The mark ICON_DP across (a launcher shows the middle 72 dp; at the 66 dp safe zone's full width it
  // looked too big). Not always a whole scale (51 dp is 4.5 px a pixel at xxhdpi): nearest-neighbour, so
  // some blocks come out a screen pixel wider than others but every edge stays sharp - no smoothing.
  const scale = (ICON_DP * d) / n;
  const off = Math.floor((size - Math.round(n * scale)) / 2);
  const img = png(size, (x, y) => {
    const gx = Math.floor((x - off) / scale);
    const gy = Math.floor((y - off) / scale);
    const c = x >= off && y >= off && gx < n && gy < n ? iconLogo.rows[gy][gx] : '.';
    const hex = iconLogo.pal[c];
    if (!hex) return [0, 0, 0, 0];
    return [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)).concat(255);
  });
  writeFileSync(join(root, `app/src/main/res/mipmap-${name}/ic_launcher_foreground.png`), img);
  console.log(`mipmap-${name}: ${size}px, mark ${Math.round(n * scale)}px = ${((n * scale) / d).toFixed(1)} dp (x${scale.toFixed(2)})`);
}
