#!/usr/bin/env python3
"""The region maps' cursor grids - which map section each tile of the map is,
the table the game's own map cursor reads the name under it from - for the
companion's Map tab (tap a tile -> its name; a dungeon's spot on the map).

  FireRed: region_map.c's sRegionMapSections_{Kanto,Sevii123,Sevii45,Sevii67}
           [LAYER_MAP, LAYER_DUNGEON][15][22], 4 tiles in from the 30x20 screen
           (the same offset as MapSecData.kt's corners).
  Emerald: region_map.c's sRegionMap_MapSectionLayout[15][28], at
           MAPCURSOR_X_MIN / _Y_MIN = (1, 2).

Read from the pinned decomp builds by symbol, like gen_rom_art_sigs.py.
Usage: scripts/gen_region_map_layouts.py   (needs $DECOMPS/pokefirered and
$DECOMPS/pokeemerald built once; re-run only if a pin changes)
"""
import os
import subprocess

from decomps import decomp

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = decomp()
KOTLIN = os.path.join(HERE, "../app/src/main/kotlin/com/pokedaisy/app/companion/data/RegionMapLayoutsGen.kt")

# (Kotlin name, rom, elf, [symbols], layers, width, height, offset x, offset y, MAPSEC_NONE)
GAMES = [
    ("regionLayoutsFireRed", "pokefirered/pokefirered_rev1.gba", "pokefirered/pokefirered_rev1.elf",
     ["sRegionMapSections_Kanto", "sRegionMapSections_Sevii123", "sRegionMapSections_Sevii45", "sRegionMapSections_Sevii67"],
     2, 22, 15, 4, 4, 0xC5),
    ("regionLayoutsEmerald", "pokeemerald/pokeemerald.gba", "pokeemerald/pokeemerald.elf",
     ["sRegionMap_MapSectionLayout"], 1, 28, 15, 1, 2, 0xD5),
]


def symbols(elf):
    out = {}
    for line in subprocess.run(["nm", "-S", elf], capture_output=True, text=True, check=True).stdout.splitlines():
        p = line.split()
        if len(p) == 4:
            out[p[3]] = (int(p[0], 16) - 0x08000000, int(p[1], 16))
    return out


def main():
    out = []
    for name, rom_path, elf, syms, layers, w, h, ox, oy, none in GAMES:
        rom = open(os.path.join(ROOT, rom_path), "rb").read()
        table = symbols(os.path.join(ROOT, elf))
        rows = []
        for sym in syms:
            off, size = table[sym]
            assert size == layers * w * h, (sym, size)
            grids = [rom[off + i * w * h:off + (i + 1) * w * h].hex() for i in range(layers)]
            rows.append(f"    RegionLayout({ox}, {oy}, {w}, {h}, 0x{none:02X}, listOf(\n" +
                        "".join(f'        hexBytes("{g}"),\n' for g in grids) + "    )),")
            print(f"{name}: {sym} @{off:#x}")
        out.append(f"internal val {name}: List<RegionLayout> = listOf(\n" + "\n".join(rows) + "\n)\n")
    kt = """package com.pokedaisy.app.companion.data

// GENERATED by scripts/gen_region_map_layouts.py from the pinned pokefirered /
// pokeemerald builds - do not hand-edit; rerun the script instead.

""" + "\n".join(out)
    open(KOTLIN, "w").write(kt)
    print("wrote", KOTLIN)


if __name__ == "__main__":
    main()
