#!/usr/bin/env python3
"""Generates Pokémon Glazed's display tables from the ROM the user owns
(closed binary hack of Emerald, no source; nothing is downloaded).

    scripts/gen_glazed_tables.py <rom.gba>

Writes app/src/main/kotlin/.../companion/data/{SpeciesNames,SpeciesTypes,
GenderRatios,ItemNames,ItemDescriptions,MoveData,TypeChart,MapSecData}Glazed.kt.

Glazed 9.2.0 is an in-place edit of retail Emerald (BPEE rev 0): its code and
RAM are retail's, and so are almost all of its tables - every literal pool that
loads gSpeciesNames / gBaseStats / gMoveNames / gBattleMoves / gItems /
gRegionMapEntries still holds retail's address (checked word for word against
retail Emerald). It reuses the 412 species slots (CHIMCHAR is species 298,
where retail has SEEDOT), renames ~50 moves and ~85 items in place, turns
vanilla's unused type 9 ("???") into FAIRY (gTypeNames), and moved only the
type chart: gTypeEffectiveness's ten literal-pool refs point at 0x09500D50
(retail's {atk, def, x10} triplets, 0xFE separator, 0xFF end). Its map sections
are its own (Tunod, Johto, Rankor), and so is its region map - Tunod and Johto
side by side, written over retail's blobs and cursor grid (RomArt's GZ_REGION_*,
regionmap/glazed.png); a section's rect is its entry's {x, y, w, h} + (1, 2), as
in retail (Glenwood Town's (8, 4) and New Bark Town's (27, 10) are where the grid
names them).
"""
import hashlib
import os
import struct
import sys

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "src", "main", "kotlin",
                       "com", "pokedaisy", "app", "companion", "data")

SHA1 = "e10105d8544469c6a11ca2cf510289981df3c3b0"
LABEL = "Pokemon Glazed 9.2.0"

SPECIES_NAMES = 0x083185C8   # 11-byte names, retail's
BASE_STATS = 0x083203CC      # 28-byte gBaseStats: types +6/+7, genderRatio +16
MOVE_NAMES = 0x0831977C      # 13-byte names
BATTLE_MOVES = 0x0831C898    # 12-byte gBattleMoves: power +1, type +2
ITEMS = 0x085839A0           # 44-byte struct Item: name[14], description ptr +0x14
TYPE_CHART = 0x09500D50      # repointed
REGION_MAP_ENTRIES = 0x085A147C  # {x, y, w, h, name ptr}
MAP_SECTION_LAYOUT = 0x085A096C  # sRegionMap_MapSectionLayout [15][28], its own
GRID_W, GRID_H, GRID_X, GRID_Y = 28, 15, 1, 2  # retail's grid, placed on the screen as retail's
SPECIES_COUNT = 412          # SPECIES_EGG
MOVE_COUNT = 355
ITEM_COUNT = 377
MAPSEC_COUNT = 0xD5          # MAPSEC_NONE

TYPE_NAMES = {0: "Normal", 1: "Fighting", 2: "Flying", 3: "Poison", 4: "Ground", 5: "Rock", 6: "Bug", 7: "Ghost",
              8: "Steel", 9: "Fairy", 10: "Fire", 11: "Water", 12: "Grass", 13: "Electric", 14: "Psychic",
              15: "Ice", 16: "Dragon", 17: "Dark"}

CHARS = {0x00: " ", 0x1B: "é", 0xAB: "!", 0xAC: "?", 0xAD: ".", 0xAE: "-", 0xB0: "…", 0xB1: "“", 0xB2: "”",
         0xB3: "'", 0xB4: "'", 0xB5: "♂", 0xB6: "♀", 0xB8: ",", 0xBA: "/", 0xF0: ":", 0x2D: "&", 0x5C: "(",
         0x5D: ")", 0x5B: "%", 0x35: "=", 0x36: ";", 0x53: "PK", 0x54: "MN"}
# Line / paragraph breaks: descriptions are wrapped for the game's box, the app rewraps.
CHARS.update({0xFA: " ", 0xFB: " ", 0xFE: " "})
CHARS.update({0xA1 + i: str(i) for i in range(10)})
CHARS.update({0xBB + i: chr(65 + i) for i in range(26)})
CHARS.update({0xD5 + i: chr(97 + i) for i in range(26)})

# Spot checks against what the game shows (the user's save: CHIMCHAR with
# SCRATCH / LEER / EMBER, its map FOREST PASS).
CHECKS = dict(species={4: "CHARMANDER", 298: "CHIMCHAR", 410: "ARCEUS"}, types={35: (9, 9), 298: (10, 10)},
              moves={10: ("SCRATCH", 0, 40), 52: ("EMBER", 10, 40)}, items={1: "MASTER BALL", 168: "GLAZED DONUT"},
              mapsecs={0x00: "Glenwood Town", 0x11: "Forest Pass"})


def text(rom, a, maxlen):
    out = []
    for b in rom[a - 0x08000000:a - 0x08000000 + maxlen]:
        if b == 0xFF:
            break
        if b not in CHARS:
            return None
        out.append(CHARS[b])
    s = " ".join("".join(out).split())
    return s if s and set(s) != {"?"} and s != "-" else None


def u8(rom, a):
    return rom[a - 0x08000000]


def u32(rom, a):
    return struct.unpack_from("<I", rom, a - 0x08000000)[0]


def is_ptr(rom, v):
    return 0x08000000 <= v < 0x08000000 + len(rom)


def kstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def title(s):
    words = []
    for w in s.split(" "):
        words.append(w if w.count(".") >= 2 else w[:1] + w[1:].lower())
    return " ".join(words)


def header(what):
    return (f"package com.pokedaisy.app.companion.data\n\n"
            f"// GENERATED by scripts/gen_glazed_tables.py from the {LABEL} ROM\n"
            f"// (sha1 {SHA1[:8]}...) - do not hand-edit. {what}\n")


def write(name, body):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w") as f:
        f.write(body)
    print("wrote", os.path.relpath(path))


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <rom.gba>")
    rom = open(sys.argv[1], "rb").read()
    if hashlib.sha1(rom).hexdigest() != SHA1:
        sys.exit(f"not {LABEL} (sha1 {SHA1})")

    names, types, gender = {}, {}, {}
    for i in range(1, SPECIES_COUNT):
        n = text(rom, SPECIES_NAMES + 11 * i, 11)
        if not n:
            continue
        names[i] = n
        b = BASE_STATS + 28 * i
        types[i] = (u8(rom, b + 6), u8(rom, b + 7))
        gender[i] = u8(rom, b + 16)
    assert all(names.get(i) == n for i, n in CHECKS["species"].items()), "species names are wrong"
    assert all(types.get(i) == t for i, t in CHECKS["types"].items()), "species types are wrong"
    write("SpeciesNamesGlazed.kt", header("gSpeciesNames, keyed by the game's own species\n"
          "// ids (retail's 412 slots, many holding other species).\n") +
          "val speciesNamesGlazed: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(names.items())) + ")\n")
    write("SpeciesTypesGlazed.kt", header("gBaseStats types, ids per typeNamesGlazed.\n") +
          "val speciesTypeDataGlazed: Map<Int, SpeciesTypes> = mapOf(\n" +
          "".join(f"    {i} to SpeciesTypes({a}, {b}),\n" for i, (a, b) in sorted(types.items())) + ")\n")
    hexs = "".join("%02x" % gender.get(i, 255) for i in range(max(gender) + 1))
    write("GenderRatiosGlazed.kt", header("gBaseStats genderRatio by species id (0 always\n"
          "// male, 254 always female, 255 genderless, else female when (personality & 0xFF) < ratio).\n") +
          f"val genderRatiosGlazed: IntArray by lazy {{ unhexRatios(\"{hexs}\") }}\n")

    moves = []
    for i in range(1, MOVE_COUNT):
        n = text(rom, MOVE_NAMES + 13 * i, 13)
        if n:
            b = BATTLE_MOVES + 12 * i
            moves.append((i, n, u8(rom, b + 2), u8(rom, b + 1)))
    info = {i: (n, t, p) for i, n, t, p in moves}
    assert all(info.get(i) == v for i, v in CHECKS["moves"].items()), "moves are wrong"
    write("MoveDataGlazed.kt", header("gMoveNames + gBattleMoves type / power.\n") +
          "val moveDataGlazed: Map<Int, MoveInfo> = mapOf(\n" +
          "".join(f"    {i} to MoveInfo({kstr(n)}, {t}, {p}),\n" for i, n, t, p in moves) + ")\n")

    items, descs = {}, {}
    for i in range(1, ITEM_COUNT):
        a = ITEMS + 44 * i
        n = text(rom, a, 14)
        if not n:
            continue
        items[i] = n
        p = u32(rom, a + 0x14)
        d = text(rom, p, 200) if is_ptr(rom, p) else None
        if d:
            descs[i] = d
    assert all(items.get(i) == n for i, n in CHECKS["items"].items()), "item names are wrong"
    write("ItemNamesGlazed.kt", header("gItems names, keyed by item id.\n") +
          "val itemNamesGlazed: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(n)},\n" for i, n in sorted(items.items())) + ")\n")
    write("ItemDescriptionsGlazed.kt", header("gItems descriptions, keyed by item id.\n") +
          "val itemDescriptionsGlazed: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(d)},\n" for i, d in sorted(descs.items())) + ")\n")

    chart = {}
    a = TYPE_CHART
    while u8(rom, a) != 0xFF:
        atk, dfn, mult = u8(rom, a), u8(rom, a + 1), u8(rom, a + 2)
        a += 3
        if atk == 0xFE:  # TYPE_FORESIGHT: the Ghost immunities after it still apply
            continue
        chart[atk * 100 + dfn] = mult * 10
    assert chart[10 * 100 + 12] == 200 and chart[0 * 100 + 7] == 0 and chart[16 * 100 + 9] == 0, "chart is wrong"
    write("TypeChartGlazed.kt", header("Retail's type ids with 9 (\"???\") as FAIRY. The chart\n"
          "// is gTypeEffectiveness's {atk, def, x10} triplets; key = atkType*100+defType -> percent, pairs\n"
          "// not listed are 100.\n") +
          "val typeNamesGlazed: Map<Int, String> = mapOf(\n" +
          "".join(f"    {i} to {kstr(s)},\n" for i, s in sorted(TYPE_NAMES.items())) + ")\n\n" +
          "val typeEffectivenessGlazed: Map<Int, Int> = mapOf(\n" +
          "".join(f"    {k} to {v},\n" for k, v in chart.items()) + ")\n")

    mapsecs, rows = {}, []
    grid = rom[MAP_SECTION_LAYOUT - 0x08000000:MAP_SECTION_LAYOUT - 0x08000000 + GRID_W * GRID_H]
    on_grid = set(grid) - {MAPSEC_COUNT}
    for i in range(MAPSEC_COUNT):
        a = REGION_MAP_ENTRIES + 8 * i
        p = u32(rom, a + 4)
        s = text(rom, p, 20) if is_ptr(rom, p) else None
        if not s:
            continue
        mapsecs[i] = title(s)
        x, y, w, h = (u8(rom, a + k) for k in range(4))
        # 255 / 255 and 0 / 0 are "not on the map", unless the grid names the section.
        if x < GRID_W and y < GRID_H and (x, y) != (0, 0) and w and h:
            rows.append(f"    {i} to MapSecInfo({kstr(mapsecs[i])}, 0, {x + GRID_X}, {y + GRID_Y}, {w}, {h}),\n")
        elif i in on_grid:
            rows.append(f"    {i} to MapSecInfo({kstr(mapsecs[i])}, 0, 0, 0, 0, 0),\n")
        else:
            rows.append(f"    {i} to MapSecInfo({kstr(mapsecs[i])}, -1, 0, 0, 0, 0),\n")
    assert all(mapsecs.get(i) == n for i, n in CHECKS["mapsecs"].items()), "map sections are wrong"
    assert on_grid <= set(mapsecs), sorted(on_grid - set(mapsecs))
    assert grid[4 * GRID_W + 8] == 0x00 and grid[10 * GRID_W + 27] == 0x29, "grid is wrong"
    write("MapSecDataGlazed.kt", header("gRegionMapEntries by mapsec id, rects in 8px\n"
          "// tiles on regionmap/glazed.png (RomArt rebuilds it from the ROM); region -1 = not on the map.\n"
          "// The grid is its sRegionMap_MapSectionLayout, for the map cursor.\n") +
          "val regionMapImagesGlazed = arrayOf(\"glazed\")\n\n" +
          "val mapSecDataGlazed: Map<Int, MapSecInfo> = mapOf(\n" + "".join(rows) + ")\n\n" +
          "internal val regionLayoutsGlazed: List<RegionLayout> = listOf(\n"
          f"    RegionLayout({GRID_X}, {GRID_Y}, {GRID_W}, {GRID_H}, 0x{MAPSEC_COUNT:02X}, listOf(\n"
          f"        hexBytes(\"{grid.hex()}\"),\n"
          "    )),\n)\n")
    print(f"{len(names)} species, {len(moves)} moves, {len(items)} items, {len(chart)} chart pairs, "
          f"{len(mapsecs)} map sections")


if __name__ == "__main__":
    main()
