#!/usr/bin/env python3
"""Generates companion/data/ExpTables.kt - each species' growth rate and the
game's EXP-per-level tables - from a pokefirered checkout at the pinned commit
(c75f352304d529f6ba92d4f74b9cf8b5c3810788; build.sh leaves one in
$DECOMPS/pokefirered). Gen 3 shares both across FireRed/LeafGreen/Emerald, keyed
by the internal species index (Treecko = 277), so the table serves both.

Inputs:
  include/constants/species.h        SPECIES_* -> internal index
  src/data/pokemon/species_info.h    [SPECIES_X] = { ... .growthRate = GROWTH_Y ... }
  src/data/pokemon/experience_tables.h  gExperienceTables[6][101] (macros evaluated
                                        here with C integer semantics)

Usage: scripts/gen_exp_tables.py [path/to/pokefirered]
"""
import os
import re
import sys

from decomps import decomp

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else decomp("pokefirered")
OUT = os.path.join(HERE, "../app/src/main/kotlin/com/pokedaisy/app/companion/data/ExpTables.kt")

GROWTH = ["GROWTH_MEDIUM_FAST", "GROWTH_ERRATIC", "GROWTH_FLUCTUATING",
          "GROWTH_MEDIUM_SLOW", "GROWTH_FAST", "GROWTH_SLOW"]


def read(rel):
    with open(os.path.join(SRC, rel)) as f:
        return f.read()


def cdiv(a, b):
    """C integer division (truncates toward zero)."""
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b >= 0) else -q


def cube(n):
    return n * n * n


EXP = {
    "EXP_SLOW": lambda n: cdiv(5 * cube(n), 4),
    "EXP_FAST": lambda n: cdiv(4 * cube(n), 5),
    "EXP_MEDIUM_FAST": lambda n: cube(n),
    "EXP_MEDIUM_SLOW": lambda n: cdiv(6 * cube(n), 5) - 15 * n * n + 100 * n - 140,
    "EXP_ERRATIC": lambda n: (cdiv((100 - n) * cube(n), 50) if n <= 50 else
                              cdiv((150 - n) * cube(n), 100) if n <= 68 else
                              cdiv(cdiv(1911 - 10 * n, 3) * cube(n), 500) if n <= 98 else
                              cdiv((160 - n) * cube(n), 100)),
    "EXP_FLUCTUATING": lambda n: (cdiv((cdiv(n + 1, 3) + 24) * cube(n), 50) if n <= 15 else
                                  cdiv((n + 14) * cube(n), 50) if n <= 36 else
                                  cdiv((cdiv(n, 2) + 32) * cube(n), 50)),
}


def species_ids():
    ids = {}
    for m in re.finditer(r"#define (SPECIES_\w+)\s+(\d+)\b", read("include/constants/species.h")):
        ids[m.group(1)] = int(m.group(2))
    return ids


def growth_rates(ids):
    text = read("src/data/pokemon/species_info.h")
    rates = {}
    # One chunk per "[SPECIES_X] =" entry, up to the next one.
    parts = re.split(r"\[(SPECIES_\w+)\]\s*=", text)
    for name, body in zip(parts[1::2], parts[2::2]):
        g = re.search(r"\.growthRate\s*=\s*(GROWTH_\w+)", body)
        if g and name in ids and name != "SPECIES_NONE":
            rates[ids[name]] = GROWTH.index(g.group(1))
    # The OLD_UNOWN placeholders use a macro; they're Medium Fast like it says.
    return rates


def exp_tables():
    text = read("src/data/pokemon/experience_tables.h")
    body = text[text.index("gExperienceTables"):]
    tables = []
    for block in re.findall(r"\{\s*//[^\n]*\n(.*?)\n\s*\}", body, re.S):
        row = []
        for tok in re.findall(r"(EXP_\w+)\((\d+)\)|^\s*(\d+),", block, re.M):
            macro, n, lit = tok
            row.append(EXP[macro](int(n)) if macro else int(lit))
        tables.append(row)
    # Two trailing unused Medium Fast copies follow the six real tables.
    return tables[:6]


def main():
    ids = species_ids()
    rates = growth_rates(ids)
    tables = exp_tables()
    assert len(tables) == 6 and all(len(t) == 101 for t in tables), [len(t) for t in tables]
    n_species = ids["SPECIES_CHIMECHO"]  # last real species
    assert len([s for s in rates if 1 <= s <= n_species]) >= 386, len(rates)
    # Spot checks against known values.
    assert rates[ids["SPECIES_CHARIZARD"]] == 3 and rates[ids["SPECIES_LAPRAS"]] == 5
    assert tables[3][54] == 150_476 and tables[0][18] == 5_832 and tables[5][50] == 156_250

    rate_list = [rates.get(s, 0) for s in range(n_species + 1)]
    lines = [
        "package com.pokedaisy.app.companion.data",
        "",
        "// GENERATED by scripts/gen_exp_tables.py from pokefirered (species_info.h growthRate,",
        "// experience_tables.h) - do not hand-edit. Gen 3 vanilla: FireRed/LeafGreen/Emerald,",
        "// keyed by the internal species index.",
        "",
        "/** Growth rate (GROWTH_* 0..5) per internal species index, 0..SPECIES_CHIMECHO. */",
        "val gen3GrowthRates: ByteArray = byteArrayOf(",
    ]
    for i in range(0, len(rate_list), 32):
        lines.append("    " + ", ".join(str(r) for r in rate_list[i:i + 32]) + ",")
    lines += [")", "", "/** gExperienceTables[growthRate][level]: total EXP to reach that level. */",
              "val gen3ExperienceTables: Array<IntArray> = arrayOf("]
    for t in tables:
        lines.append("    intArrayOf(")
        for i in range(0, 101, 10):
            lines.append("        " + ", ".join(str(v) for v in t[i:i + 10]) + ",")
        lines.append("    ),")
    lines += [")", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(rate_list)} species, {len(tables)} tables")


if __name__ == "__main__":
    main()
