package com.pokedaisy.app.companion.data

/**
 * Which game the app is currently reading. FireRed QoL exports a packed
 * gQolTelemetry struct (decodeTelemetry); Pokémon Unbound has none, so it's
 * read from native RAM (UnboundReader) with its own data tables extracted from
 * the Unbound ROM (*Unbound.kt, generated by
 * tools/telemetry-viewer/scripts/gen_unbound_data.py). Mirrors
 * tools/telemetry-viewer/game.go.
 */
// EMERALD shares FireRed's Gen 3 species/move/item/type tables (same internal
// indices) but has its own Hoenn region map + map-section names. GAIA and
// RADICAL_RED are FireRed-based hacks read the same way as vanilla FireRed
// (NATIVE_GAIA_V3_2 / NATIVE_RADICAL_RED_V4_1 in NativeReader.kt). Gaia
// relocated + grew its species table wholesale (see SpeciesNamesGaia.kt).
// Radical Red repoints its own tables (gSpeciesNames with its own ids up to
// 1349, long move names, gItems, gBaseStats): all read from its ROM by
// scripts/gen_cfru_tables.py, so none fall back to vanilla's.
// ODYSSEY - basic connectivity only so far (NATIVE_ODYSSEY inherits every
// vanilla FireRed RAM address unchanged, unverified beyond a live party/item
// check - see NativeReader.kt). Whether it renumbers species/items enough to
// need its own name tables (like Gaia/Radical Red did) hasn't been checked yet -
// falls through to the shared vanilla tables below (`else`) until it has.
// HEART_AND_SOUL/LAZARUS/ROWE are Emerald-based hacks (BPEE) - the first ones
// this project has supported; same "inherit NATIVE_EMERALD unchanged, verify
// live, re-derive only what's actually broken" starting point as the FireRed
// hacks above, via NATIVE_HEART_AND_SOUL/NATIVE_LAZARUS/NATIVE_ROWE in
// NativeReader.kt. Heart and Soul and Lazarus now have their own
// ROM-extracted tables (*Hns.kt / *Lazarus.kt, scripts/gen_expansion_tables.py).
enum class GameKind { FIRERED, EMERALD, UNBOUND, GAIA, RADICAL_RED, ODYSSEY, HEART_AND_SOUL, LAZARUS, ROWE, EMERALD_ROGUE, AMETHYST, EMERALD_SEAGLASS, CELIA, TMT2, SOULGOLD, YELLOW, GLAZED, IMPERIUM, QUETZAL, ORANGE_ISLANDS }

@Volatile
var activeGame: GameKind = GameKind.FIRERED

private inline val unbound get() = activeGame == GameKind.UNBOUND
private inline val emerald get() = activeGame == GameKind.EMERALD

/** The running ROM's language letter (its game code's last: BPE<S|D|F|I|J>); 'E' for English
 * and everything else. Set with [activeGame] by the Poller. */
var romLanguage = 'E'

/** The running retail ROM's game code when it has names of its own ("BPED", "AXVF"); else "". */
var romGameCode = ""

/** The running game's own names (EmeraldLanguages.kt); null for English and every game without them. */
val localText: GameText? get() = if (romGameCode.isEmpty()) null else gameText(romGameCode)

/** [shown]'s English name - what hand-written GUIDE entries tag areas with - for map section [mapsec]. */
fun englishMapSecName(mapsec: Int, shown: String): String =
    localText?.let { it.baseMapSecs[mapsec]?.name }
        ?: (if (activeGame == GameKind.QUETZAL && quetzalNames.places != 0) mapSecDataQuetzal[mapsec]?.name else null)
        ?: shown
private inline val seaglass get() = activeGame == GameKind.EMERALD_SEAGLASS
private inline val celia get() = activeGame == GameKind.CELIA
private inline val tmt2 get() = activeGame == GameKind.TMT2
private inline val hns get() = activeGame == GameKind.HEART_AND_SOUL
private inline val lazarus get() = activeGame == GameKind.LAZARUS
private inline val soulGold get() = activeGame == GameKind.SOULGOLD
// Pokémon Glazed: retail Emerald's engine and ids, its own names in them (gen_glazed_tables.py).
private inline val glazed get() = activeGame == GameKind.GLAZED
private inline val imperium get() = activeGame == GameKind.IMPERIUM
private inline val quetzal get() = activeGame == GameKind.QUETZAL
private inline val rowe get() = activeGame == GameKind.ROWE
// Pokémon Orange Islands: FireRed 1.0 edited in place, its own names / types / chart (gen_orange_islands_tables.py).
private inline val orangeIslands get() = activeGame == GameKind.ORANGE_ISLANDS
// Pokémon Yellow (Game Boy): Gen 1's own tables (gen_gen1_tables.py), keyed by National Dex number.
private inline val yellow get() = activeGame == GameKind.YELLOW

/** SoulGold v1.2 runs on v1.1.4's tables (byte for byte the same) but for one TM: its
 * TM75 teaches Agility, not Swords Dance. Set with [activeGame] by the Poller. */
var soulGoldV12 = false
private val itemNamesSoulGoldV12 by lazy { itemNamesSoulGold + (SOULGOLD_V12_TM75 to "TM75 Agility") }
internal const val SOULGOLD_V12_TM75 = 656
/** Amethyst v1.4.1 renumbered species past 1233 (26 Hisuian forms inserted) and filled
 * ~90 item slots: its own tables. Set with [activeGame] by the Poller. */
var amethystV141 = false
private inline val gaia get() = activeGame == GameKind.GAIA
private inline val radicalRed get() = activeGame == GameKind.RADICAL_RED
private inline val amethyst get() = activeGame == GameKind.AMETHYST
private inline val odyssey get() = activeGame == GameKind.ODYSSEY
// CFRU-family hacks with CFRU's own type ids (Fairy = 23, as in Unbound) -
// checked in each ROM's base stats (CLEFAIRY is 23/23).
private inline val cfruTypes get() = radicalRed || amethyst || gaia
// Hacks confirmed to store species as the plain National Dex number (see
// SpeciesNamesNationalDex.kt) rather than vanilla's internal Gen3 index.
private inline val nationalDexSpecies get() =
    activeGame == GameKind.EMERALD_ROGUE || activeGame == GameKind.EMERALD_SEAGLASS
// Hacks confirmed to renumber items vs vanilla with no id->name table of
// their own yet - fall back to itemName()'s "Item#N" default rather than
// showing a wrong vanilla name that happens to share the numeric id
// (confirmed wrong for Lazarus: its real item id 28 isn't vanilla's
// "Lemonade").
private inline val rogue get() = activeGame == GameKind.EMERALD_ROGUE

// Odyssey reuses vanilla's unused "???" type (9) as Fairy (CLEFAIRY is 9/9).
private val typeNamesOdyssey: Map<Int, String> by lazy { typeNames + (9 to "Fairy") }

private val speciesNamesOdysseyMerged: Map<Int, String> by lazy { speciesNames + speciesNamesOdyssey }

val activeSpeciesNames: Map<Int, String> get() = localText?.species ?: when {
    yellow -> speciesNamesYellow
    unbound -> speciesNamesUnbound
    gaia -> speciesNamesGaia
    radicalRed -> speciesNamesRadicalRed
    odyssey -> speciesNamesOdysseyMerged
    // Rogue's ids are National Dex numbers only up to 905 (forms, then Gen 9 from 1289): its own names.
    rogue -> speciesNamesRogue
    nationalDexSpecies -> speciesNamesNationalDex
    amethyst -> if (amethystV141) speciesNamesAmethystV141 else speciesNamesAmethyst
    celia -> speciesNamesCelia
    tmt2 -> speciesNamesTmt2
    hns -> speciesNamesHns
    lazarus -> speciesNamesLazarus
    soulGold -> speciesNamesSoulGold
    glazed -> speciesNamesGlazed
    imperium -> speciesNamesImperium
    quetzal -> if (quetzalNames.species != 0) speciesNamesQuetzalSpanish else speciesNamesQuetzal
    rowe -> speciesNamesRowe
    orangeIslands -> speciesNamesOrangeIslands
    else -> speciesNames
}
val activeMoveData: Map<Int, MoveInfo> get() = localText?.moveData ?: when {
    yellow -> moveDataYellow
    unbound -> moveDataUnbound
    celia -> moveDataCelia
    tmt2 -> moveDataTmt2
    hns -> moveDataHns
    lazarus -> moveDataLazarus
    seaglass -> moveDataSeaglass
    soulGold -> moveDataSoulGold
    rogue -> moveDataRogue
    radicalRed -> moveDataRadicalRed
    glazed -> moveDataGlazed
    imperium -> moveDataImperium
    quetzal -> quetzalMoves(quetzalNames.moves)
    rowe -> moveDataRowe
    orangeIslands -> moveDataOrangeIslands
    else -> moveData
}
val activeItemNames: Map<Int, String> get() = localText?.items ?: when {
    yellow -> itemNamesYellow
    unbound -> itemNamesUnbound
    amethyst -> if (amethystV141) itemNamesAmethystV141 else itemNamesAmethyst
    seaglass -> itemNamesSeaglass
    celia -> itemNamesCelia
    tmt2 -> itemNamesTmt2
    hns -> itemNamesHns
    lazarus -> itemNamesLazarus
    soulGold -> if (soulGoldV12) itemNamesSoulGoldV12 else itemNamesSoulGold
    rogue -> itemNamesRogue
    radicalRed -> itemNamesRadicalRed
    glazed -> itemNamesGlazed
    imperium -> itemNamesImperium
    quetzal -> quetzalItems(quetzalNames.items)
    rowe -> itemNamesRowe
    orangeIslands -> itemNamesOrangeIslands
    else -> itemNames
}
val activeSpeciesTypeData: Map<Int, SpeciesTypes> get() = when {
    yellow -> speciesTypeDataYellow
    unbound -> speciesTypeDataUnbound
    tmt2 -> speciesTypeDataTmt2
    hns -> speciesTypeDataHns
    lazarus -> speciesTypeDataLazarus
    seaglass -> speciesTypeDataSeaglass
    soulGold -> speciesTypeDataSoulGold
    celia -> speciesTypeDataCelia
    rogue -> speciesTypeDataRogue
    radicalRed -> speciesTypeDataRadicalRed
    glazed -> speciesTypeDataGlazed
    imperium -> speciesTypeDataImperium
    quetzal -> speciesTypeDataQuetzal
    rowe -> speciesTypeDataRowe
    orangeIslands -> speciesTypeDataOrangeIslands
    else -> speciesTypeData
}
val activeTypeEffectiveness: Map<Int, Int> get() = when {
    yellow -> typeEffectivenessYellow
    unbound || cfruTypes -> typeEffectivenessUnbound
    // Seaglass uses the standard expansion type ids (TORCHIC is 11 = Fire), as Heart and Soul does.
    seaglass -> typeEffectivenessHns
    tmt2 -> typeEffectivenessTmt2
    hns -> typeEffectivenessHns
    lazarus -> typeEffectivenessLazarus
    soulGold -> typeEffectivenessSoulGold
    celia -> typeEffectivenessCelia
    rogue -> typeEffectivenessRogue
    glazed -> typeEffectivenessGlazed
    imperium -> typeEffectivenessImperium
    quetzal -> typeEffectivenessQuetzal
    rowe -> typeEffectivenessRowe
    orangeIslands -> typeEffectivenessOrangeIslands
    else -> typeEffectiveness
}
val activeTypeNames: Map<Int, String> get() = when {
    yellow -> typeNamesYellow
    unbound || cfruTypes -> typeNamesUnbound
    odyssey -> typeNamesOdyssey
    seaglass -> typeNamesHns
    tmt2 -> typeNamesTmt2
    hns -> typeNamesHns
    lazarus -> typeNamesLazarus
    soulGold -> typeNamesSoulGold
    celia -> typeNamesCelia
    rogue -> typeNamesRogue
    glazed -> typeNamesGlazed
    imperium -> typeNamesImperium
    quetzal -> typeNamesQuetzal
    rowe -> typeNamesRowe
    orangeIslands -> typeNamesOrangeIslands
    else -> typeNames
}
val activeMapSecData: Map<Int, MapSecInfo> get() = localText?.mapSecData ?: when {
    yellow -> mapSecDataYellow
    unbound -> mapSecDataUnbound
    // Seaglass keeps vanilla Hoenn mapsec ids (0x00 = Littleroot, confirmed live).
    emerald || seaglass || tmt2 -> mapSecDataEmerald
    // Own regions' names, text-only (no region-map image yet).
    hns -> mapSecDataHns
    lazarus -> mapSecDataLazarus
    soulGold -> mapSecDataSoulGold
    rogue -> mapSecDataRogue
    glazed -> mapSecDataGlazed
    imperium -> mapSecDataImperium
    quetzal -> quetzalMapSecs(quetzalNames.places)
    rowe -> mapSecDataRowe
    orangeIslands -> mapSecDataOrangeIslands
    else -> mapSecData
}
/**
 * Quetzal's Kanto and Sevii maps are FireRed's, pixel for pixel, drawn 3 tiles left and 2 up of
 * FireRed's screen (RomArt's QTZ_*: regionmap/quetzal_*.png), and its map sections keep FireRed's
 * ids: FireRed's rects and cursor grids, shifted, under Quetzal's own names.
 */
private const val QUETZAL_MAP_DX = -3
private const val QUETZAL_MAP_DY = -2
private val regionMapImagesQuetzalOnMap = arrayOf("quetzal_kanto", "quetzal_sevii123", "quetzal_sevii45", "quetzal_sevii67")
private val mapSecDataQuetzalOnMap: Map<Int, MapSecInfo> by lazy {
    mapSecDataQuetzal.mapValues { (id, q) ->
        val fr = mapSecData[id] ?: return@mapValues q
        if (fr.region < 0) q
        else if (fr.w == 0) q.copy(region = fr.region)  // placed by the grid alone
        else q.copy(region = fr.region, x = fr.x + QUETZAL_MAP_DX, y = fr.y + QUETZAL_MAP_DY, w = fr.w, h = fr.h)
    }
}
internal val regionLayoutsQuetzal: List<RegionLayout> by lazy {
    regionLayoutsFireRed.map { RegionLayout(it.offX + QUETZAL_MAP_DX, it.offY + QUETZAL_MAP_DY, it.w, it.h, it.none, it.layers, it.cellBytes) }
}

/**
 * Which language Quetzal shows each kind of name in - its own START > OPCIONES > TEXTO > IDIOMA
 * options, read from the save every sample ([readQuetzalNames]; set by the Poller): 0 English,
 * 1 Spanish, 2 Latin American Spanish (Portuguese, 3, isn't generated: English). Its Spanish
 * release only changes the LUGARES default. [QuetzalNamesGen.kt] holds the names that differ.
 */
@Volatile
var quetzalNames = QuetzalNames()

private val speciesNamesQuetzalSpanish by lazy { speciesNamesQuetzal + speciesNamesQuetzalEs }
private val moveDataQuetzalEs by lazy { moveDataQuetzal.renamed(moveNamesQuetzalEs) }
private val moveDataQuetzalLa by lazy { moveDataQuetzal.renamed(moveNamesQuetzalLa) }
private val itemNamesQuetzalSpanish by lazy { itemNamesQuetzal + itemNamesQuetzalEs }
private val itemNamesQuetzalLatam by lazy { itemNamesQuetzal + itemNamesQuetzalLa }
private val mapSecDataQuetzalEs by lazy { mapSecDataQuetzalOnMap.renamedSecs(mapSecNamesQuetzalEs) }
private val mapSecDataQuetzalLa by lazy { mapSecDataQuetzalOnMap.renamedSecs(mapSecNamesQuetzalLa) }

private fun Map<Int, MoveInfo>.renamed(names: Map<Int, String>) = mapValues { (id, m) -> names[id]?.let { m.copy(name = it) } ?: m }
private fun Map<Int, MapSecInfo>.renamedSecs(names: Map<Int, String>) = mapValues { (id, m) -> names[id]?.let { m.copy(name = it) } ?: m }

private fun quetzalMoves(lang: Int) = when (lang) { 1 -> moveDataQuetzalEs; 2 -> moveDataQuetzalLa; else -> moveDataQuetzal }
private fun quetzalItems(lang: Int) = when (lang) { 1 -> itemNamesQuetzalSpanish; 2 -> itemNamesQuetzalLatam; else -> itemNamesQuetzal }
private fun quetzalMapSecs(lang: Int) = when (lang) { 1 -> mapSecDataQuetzalEs; 2 -> mapSecDataQuetzalLa; else -> mapSecDataQuetzalOnMap }

// Seaglass's own Hoenn art (RomArt's regionmap/seaglass.png) on Emerald's tilemap and grid.
private val regionMapImagesSeaglass = arrayOf("seaglass")

val activeRegionMapImages: Array<String> get() = when {
    yellow -> arrayOf("yellow")   // its town map, rebuilt from the ROM (Gen1Art)
    unbound -> regionMapImagesUnbound
    seaglass -> regionMapImagesSeaglass
    emerald || tmt2 -> regionMapImagesEmerald
    hns -> regionMapImagesHns
    lazarus -> regionMapImagesLazarus
    soulGold -> regionMapImagesSoulGold
    rogue -> regionMapImagesRogue
    glazed -> regionMapImagesGlazed
    imperium -> regionMapImagesImperium
    quetzal -> regionMapImagesQuetzalOnMap
    rowe -> regionMapImagesRowe
    // Its own Orange Archipelago, drawn from the ROM (RomRegionMap) - none bundled.
    orangeIslands -> emptyArray()
    else -> regionMapImages
}

/**
 * Unbound reindexes species/items vs vanilla so the bundled Gen 3 PNGs don't
 * match it. Mon + item icons are fetched live from the running game and cached
 * (UnboundIconSource), like its region map (RomRegionMap).
 */
val activeMonSpriteDir: String get() = when {
    unbound -> "pokemon-unbound"
    yellow -> Gen1Art.YELLOW_ICONS   // its own party icons, rebuilt from the ROM
    else -> "pokemon"
}
val activeItemSpriteDir: String? get() = when {
    unbound -> "items-unbound"
    yellow -> null   // Gen 1 has no item icons
    else -> "items"
}

fun parseGameKind(s: String?): GameKind =
    if (s.equals("unbound", ignoreCase = true)) GameKind.UNBOUND else GameKind.FIRERED

/** Human-readable label for the Settings screen ("current game" display) -
 * distinct from the enum's own name (RADICAL_RED, not "Radical Red"). */
fun GameKind.displayName(): String = when (this) {
    GameKind.FIRERED -> "FireRed"
    GameKind.EMERALD -> "Emerald"
    GameKind.UNBOUND -> "Pokémon Unbound"
    GameKind.GAIA -> "Pokémon Gaia"
    GameKind.RADICAL_RED -> "Pokémon Radical Red"
    GameKind.ODYSSEY -> "Pokémon Odyssey"
    GameKind.HEART_AND_SOUL -> "Pokémon Heart and Soul"
    GameKind.LAZARUS -> "Pokémon Lazarus"
    GameKind.ROWE -> "Pokémon R.O.W.E."
    GameKind.EMERALD_ROGUE -> "Emerald Rogue"
    GameKind.AMETHYST -> "Pokémon Amethyst"
    GameKind.EMERALD_SEAGLASS -> "Emerald Seaglass"
    GameKind.CELIA -> "Celia's Stupid Romhack"
    GameKind.TMT2 -> "Too Many Types 2"
    GameKind.SOULGOLD -> "Pokémon SoulGold"
    GameKind.YELLOW -> "Pokémon Yellow"
    GameKind.GLAZED -> "Pokémon Glazed"
    GameKind.IMPERIUM -> "Emerald Imperium"
    GameKind.QUETZAL -> "Pokémon Quetzal"
    GameKind.ORANGE_ISLANDS -> "Pokémon Orange Islands"
}
