package com.pokedaisy.app.companion.i18n.guide

import com.pokedaisy.app.companion.i18n.Tr

/** GuideRubySapphire.kt's text (see GuideText.kt): one line per English string, names as the localized games show them. */
// Only the lines Emerald's guide doesn't have: the lines both share are in GuideTextEmerald.kt.
// Names from the localized Ruby / Sapphire ROMs (their tables match Emerald's for every name used here).
val guideTextRubySapphire: Map<String, Tr> = mapOf(
    // TIPS
    "Trainers you've beaten are listed in the POKéNAV's TRAINER'S EYES. Once you have five badges, walking around makes some of them want a rematch." to Tr(ja = "たおした トレーナーは ポケナビの トレーナーアイに のる。 バッジが 5こ あれば あるきまわる うちに さいせんを のぞむ ひとが でてくる。", fr = "Les DRESSEURS battus apparaissent dans l'INFO DRESSEURS du POKéNAV. Avec cinq badges, certains voudront une revanche pendant que vous vous déplacez.", de = "Besiegte TRAINER stehen im POKéNAV unter TRAINER. Ab fünf Orden wollen manche beim Herumlaufen eine Revanche.", it = "Gli ALLENATORI sconfitti compaiono nell'opzione ALLENATORI del POKéNAV. Con cinque medaglie, mentre giri qualcuno vorrà la rivincita.", es = "Los ENTRENADORES derrotados aparecen en la sección ENTRENADORES del POKéNAV. Con cinco medallas, al caminar algunos querrán la revancha."),

    // WHERE IS
    "An item ball on CAVE OF ORIGIN B3F, on your way down to GROUDON." to Tr(ja = "めざめのほこら ちか3かいの どうぐ。 グラードンの もとへ おりる とちゅうに ある。", fr = "Un objet au 3e sous-sol de la GROTTE ORIGINE, en descendant vers GROUDON.", de = "Ein Item im 3. Untergeschoss der URZEITHÖHLE, auf dem Weg hinunter zu GROUDON.", it = "Uno strumento al 3º sotterraneo della GROTTA dei TEMPI, scendendo verso GROUDON.", es = "Un objeto en el sótano 3 de la CUEVA ANCESTRAL, bajando hacia GROUDON."),
    "An item ball on CAVE OF ORIGIN B3F, on your way down to KYOGRE." to Tr(ja = "めざめのほこら ちか3かいの どうぐ。 カイオーガの もとへ おりる とちゅうに ある。", fr = "Un objet au 3e sous-sol de la GROTTE ORIGINE, en descendant vers KYOGRE.", de = "Ein Item im 3. Untergeschoss der URZEITHÖHLE, auf dem Weg hinunter zu KYOGRE.", it = "Uno strumento al 3º sotterraneo della GROTTA dei TEMPI, scendendo verso KYOGRE.", es = "Un objeto en el sótano 3 de la CUEVA ANCESTRAL, bajando hacia KYOGRE."),
    "Under SOOTOPOLIS CITY, late in the story." to Tr(ja = "ものがたりの おわりごろ ルネシティの した。", fr = "Sous ATALANOPOLIS, tard dans l'histoire.", de = "Unter XENEROVILLE, spät in der Geschichte.", it = "Sotto CENERIDE, verso la fine della storia.", es = "Bajo ARRECÍPOLIS, al final de la historia."),
    "STEVEN hands it to you the first time you visit his house in MOSSDEEP CITY." to Tr(ja = "トクサネシティの ダイゴの いえを はじめて たずねると もらえる。", fr = "PIERRE vous la donne lors de votre première visite chez lui à ALGATIA.", de = "TROY gibt sie dir, wenn du ihn zum ersten Mal in seinem Haus in MOOSBACH CITY besuchst.", it = "Te la dà ROCCO la prima volta che vai a casa sua a VERDEAZZUPOLI.", es = "MÁXIMO te la da la primera vez que visitas su casa en CIUDAD ALGARIA."),
    "The TREASURE HUNTER's house on ROUTE 124 swaps shards found by DIVING: RED for a FIRE STONE, YELLOW for THUNDER, BLUE for WATER, GREEN for LEAF." to Tr(ja = "124ばんすいどうの ハンターの こやで ダイビングで みつけた かけらを こうかん: あかいかけらは ほのおのいし、 きいろいかけらは かみなりのいし、 あおいかけらは みずのいし、 みどりのかけらは リーフのいし。", fr = "Le CHERCHEUR DE TRESORS du CHENAL 124 échange les TESSONS trouvés en PLONGEE : ROUGE contre une PIERRE FEU, JAUNE contre une PIERREFOUDRE, BLEU contre une PIERRE EAU, VERT contre une PIERREPLANTE.", de = "Der SCHATZTAUCHER auf ROUTE 124 tauscht beim Tauchen gefundene STÜCKE: PURPUR gegen einen FEUERSTEIN, GELB gegen einen DONNERSTEIN, INDIGO gegen einen WASSERSTEIN, GRÜN gegen einen BLATTSTEIN.", it = "Il SUB CERCATESORI del PERCORSO 124 scambia i COCCI trovati con SUB: ROSSO per una PIETRAFOCAIA, GIALLO per una PIETRATUONO, BLU per una PIETRAIDRICA, VERDE per una PIETRAFOGLIA.", es = "El BUSCATESOROS MARINOS de la RUTA 124 cambia las PARTES halladas con BUCEO: ROJA por una PIEDRA FUEGO, AMARILLA por una PIEDRATRUENO, AZUL por una PIEDRA AGUA, VERDE por una PIEDRA HOJA."),
    "The WEATHER INSTITUTE on ROUTE 119 gives it to you after you drive TEAM MAGMA out." to Tr(ja = "119ばんどうろの てんきけんきゅうじょで マグマだんを おいはらった あとに もらえる。", fr = "Le CENTRE METEO de la ROUTE 119 vous le donne une fois la TEAM MAGMA chassée.", de = "Das KLIMA-INSTITUT auf ROUTE 119 gibt es dir, nachdem du TEAM MAGMA vertrieben hast.", it = "L'ISTITUTO METEO del PERCORSO 119 te lo dà dopo che hai cacciato il TEAM MAGMA.", es = "El INSTITUTO METEOROLÓGICO de la RUTA 119 te lo da tras echar al EQUIPO MAGMA."),
    "Buried in the desert." to Tr(ja = "さばくに うまって いる。", fr = "Enterrés dans le désert.", de = "In der Wüste vergraben.", it = "Sepolti nel deserto.", es = "Enterrados en el desierto."),
    "In the ROUTE 111 desert, take the ROOT or the CLAW FOSSIL (the other sinks into the sand); DEVON CORP. 2F in RUSTBORO CITY revives it." to Tr(ja = "111ばんどうろの さばくで ねっこのカセキか ツメのカセキを とる (もう ひとつは すなに しずむ)。 カナズミシティの デボンコーポレーション 2かいで ふっかつ して もらえる。", fr = "Dans le désert de la ROUTE 111, prenez le FOSS. RACINE ou le FOSS. GRIFFE (l'autre s'enfonce dans le sable) ; le 1er étage de DEVON à MEROUVILLE le ranime.", de = "Nimm in der Wüste auf ROUTE 111 das WURZELFOSSIL oder das KLAUENFOSSIL (das andere versinkt im Sand); im 1. Stock der DEVON CORPORATION in METAROST CITY wird es wiederbelebt.", it = "Nel deserto del PERCORSO 111 prendi il RADIFOSSILE o il FOSSILUNGHIA (l'altro sprofonda nella sabbia); al 1º piano della DEVON SpA a FERRUGIPOLI lo rianimano.", es = "En el desierto de la RUTA 111, coge el FÓSIL RAÍZ o el FÓSIL GARRA (el otro se hunde en la arena); en la planta 1 de DEVON S.A., en CIUDAD FÉRRICA, lo reviven."),
    "GROUDON" to Tr(ja = "グラードン", fr = "GROUDON", de = "GROUDON", it = "GROUDON", es = "GROUDON"),
    "KYOGRE" to Tr(ja = "カイオーガ", fr = "KYOGRE", de = "KYOGRE", it = "KYOGRE", es = "KYOGRE"),
    "Its cave is under SOOTOPOLIS CITY." to Tr(ja = "すみかは ルネシティの した。", fr = "Sa grotte est sous ATALANOPOLIS.", de = "Seine Höhle liegt unter XENEROVILLE.", it = "La sua grotta è sotto CENERIDE.", es = "Su cueva está bajo ARRECÍPOLIS."),
    "Lv45, at the bottom of the CAVE OF ORIGIN in SOOTOPOLIS CITY - the story takes you there." to Tr(ja = "Lv45。 ルネシティの めざめのほこらの いちばん おく。 ものがたりで いく ことに なる。", fr = "N.45, au fond de la GROTTE ORIGINE à ATALANOPOLIS : l'histoire vous y mène.", de = "Lv.45, ganz unten in der URZEITHÖHLE in XENEROVILLE - die Geschichte führt dich hin.", it = "Lv.45, in fondo alla GROTTA dei TEMPI a CENERIDE: ci arrivi con la storia.", es = "Nv.45, al fondo de la CUEVA ANCESTRAL de ARRECÍPOLIS: la historia te lleva allí."),
    "Lv70, at the top of the SKY PILLAR on ROUTE 131. Some floors crack: ride the MACH BIKE across them." to Tr(ja = "Lv70。 131ばんすいどうの そらのはしらの てっぺん。 ひびの はいった ゆかは マッハじてんしゃで わたろう。", fr = "N.70, au sommet du PILIER CELESTE (CHENAL 131). Certains sols se fissurent : traversez-les en VELO COURSE.", de = "Lv.70, ganz oben im HIMMELTURM auf ROUTE 131. Manche Böden brechen: Fahr mit dem EILRAD darüber.", it = "Lv.70, in cima alla TORRE dei CIELI sul PERCORSO 131. Alcuni pavimenti si crepano: attraversali con la BICI CORSA.", es = "Nv.70, en lo alto del PILAR CELESTE de la RUTA 131. Algunos suelos se agrietan: crúzalos con la BICI CARRERA."),
    "First open the doors: in the SEALED CHAMBER (DIVE on ROUTE 134) use DIG on the outer room's braille, then read the inner room's with RELICANTH first and WAILORD last in your party. Then, after reading each ruin's braille: DESERT RUINS (ROUTE 111) - use STRENGTH; ANCIENT TOMB (ROUTE 120) - use FLY; ISLAND CAVE (ROUTE 105) - wait two minutes without pressing anything." to Tr(ja = "まず とびらを ひらく: おふれのせきしつ (134ばんすいどうで ダイビング) の てまえの へやの てんじに あなをほるを つかい、 てもちの せんとうに ジーランス、 さいごに ホエルオーを いれて おくの へやの てんじを よむ。 つぎに それぞれの いせきの てんじを よんだ あと: さばくいせき (111ばんどうろ) は かいりき、 こだいづか (120ばんどうろ) は そらをとぶ、 こじまのよこあな (105ばんすいどう) は なにも おさずに 2ふん まつ。", fr = "Ouvrez d'abord les portes : dans le SANCTUAIRE (PLONGEE au CHENAL 134), utilisez TUNNEL sur le braille de la première salle, puis lisez celui de la salle du fond avec RELICANTH en tête et WAILORD en dernier dans l'équipe. Puis, après avoir lu le braille de chaque ruine : RUINES DESERT (ROUTE 111), utilisez FORCE ; TOMBEAU ANTIQUE (ROUTE 120), VOL ; GROTTE ISLAND (CHENAL 105), attendez deux minutes sans rien toucher.", de = "Öffne zuerst die Türen: Setz in der SIEGELKAMMER (TAUCHER auf ROUTE 134) SCHAUFLER auf die Blindenschrift im äußeren Raum ein, dann lies die im inneren Raum mit RELICANTH an erster und WAILORD an letzter Stelle im Team. Danach, nachdem du jeweils die Blindenschrift gelesen hast: WÜSTENRUINE (ROUTE 111) - setz STÄRKE ein; GRABMAL (ROUTE 120) - FLIEGEN; INSELHÖHLE (ROUTE 105) - warte zwei Minuten, ohne etwas zu drücken.", it = "Prima apri le porte: nella SALA INCISA (SUB sul PERCORSO 134) usa FOSSA sul Braille della sala esterna, poi leggi quello della sala interna con RELICANTH primo e WAILORD ultimo in squadra. Poi, dopo aver letto il Braille di ogni rovina: ROVINE SABBIOSE (PERCORSO 111) - usa FORZA; TOMBA ANTICA (PERCORSO 120) - VOLO; GROTTA INSULARE (PERCORSO 105) - aspetta due minuti senza premere nulla.", es = "Primero abre las puertas: en la CÁMARA SELLADA (BUCEO en la RUTA 134) usa EXCAVAR en el braille de la sala exterior y lee el de la sala interior con RELICANTH el primero y WAILORD el último del equipo. Después, tras leer el braille de cada ruina: RUINAS DESIERTO (RUTA 111), usa FUERZA; TUMBA ANTIGUA (RUTA 120), VUELO; CUEVA INSULAR (RUTA 105), espera dos minutos sin pulsar nada."),
    "LATIAS" to Tr(ja = "ラティアス", fr = "LATIAS", de = "LATIAS", it = "LATIAS", es = "LATIAS"),
    "LATIOS" to Tr(ja = "ラティオス", fr = "LATIOS", de = "LATIOS", it = "LATIOS", es = "LATIOS"),
    "After the HALL OF FAME, go home and watch the TV news: LATIAS starts roaming HOENN." to Tr(ja = "でんどういりの あと いえに かえって テレビの ニュースを みると ラティアスが ホウエンを かけまわりはじめる。", fr = "Après le PANTHEON DES DRESSEURS, rentrez chez vous et regardez les infos à la télé : LATIAS se met à errer dans HOENN.", de = "Geh nach der RUHMESHALLE nach Hause und sieh die Nachrichten im Fernsehen: LATIAS beginnt, durch HOENN zu streifen.", it = "Dopo la SALA d'ONORE, torna a casa e guarda il notiziario in TV: LATIAS inizia a vagare per HOENN.", es = "Tras el HALL de la FAMA, vuelve a casa y mira las noticias en la tele: LATIAS empieza a vagar por HOENN."),
    "After the HALL OF FAME, go home and watch the TV news: LATIOS starts roaming HOENN." to Tr(ja = "でんどういりの あと いえに かえって テレビの ニュースを みると ラティオスが ホウエンを かけまわりはじめる。", fr = "Après le PANTHEON DES DRESSEURS, rentrez chez vous et regardez les infos à la télé : LATIOS se met à errer dans HOENN.", de = "Geh nach der RUHMESHALLE nach Hause und sieh die Nachrichten im Fernsehen: LATIOS beginnt, durch HOENN zu streifen.", it = "Dopo la SALA d'ONORE, torna a casa e guarda il notiziario in TV: LATIOS inizia a vagare per HOENN.", es = "Tras el HALL de la FAMA, vuelve a casa y mira las noticias en la tele: LATIOS empieza a vagar por HOENN."),

    // STUCK?
    "MR. BRINEY sails you from his cottage on ROUTE 104 once you've rescued his PEEKO from TEAM MAGMA in RUSTURF TUNNEL." to Tr(ja = "カナシダトンネルで マグマだんから ピーコちゃんを たすけると 104ばんどうろの こやから ハギろうじんが ふねで つれて いって くれる。", fr = "M. MARCO vous emmène en bateau depuis son cottage de la ROUTE 104 une fois son PIKO sauvé de la TEAM MAGMA dans le TUNNEL MERAZON.", de = "MR. BRACK bringt dich von seiner Hütte auf ROUTE 104 mit dem Boot hin, sobald du sein PECKO im METAFLURTUNNEL vor TEAM MAGMA gerettet hast.", it = "Il SIG. MARINO ti porta in barca dal suo cottage sul PERCORSO 104 dopo che hai salvato il suo PEEKO dal TEAM MAGMA nel TUNNEL MENFERRO.", es = "El SR. ARENQUE te lleva en barco desde su casa de la RUTA 104 cuando rescatas a su PEEKO del EQUIPO MAGMA en el TÚNEL FERVERGAL."),
    "A TEAM MAGMA grunt fled into RUSTURF TUNNEL, east of RUSTBORO CITY. Beat him there." to Tr(ja = "マグマだんの したっぱが カナズミシティの ひがしの カナシダトンネルに にげこんだ。 そこで たおそう。", fr = "Un SBIRE de la TEAM MAGMA s'est enfui dans le TUNNEL MERAZON, à l'est de MEROUVILLE. Battez-le là-bas.", de = "Ein RÜPEL von TEAM MAGMA ist in den METAFLURTUNNEL östlich von METAROST CITY geflohen. Besiege ihn dort.", it = "Una RECLUTA del TEAM MAGMA è fuggita nel TUNNEL MENFERRO, a est di FERRUGIPOLI. Battila lì.", es = "Un SOLDADO del EQUIPO MAGMA huyó al TÚNEL FERVERGAL, al este de CIUDAD FÉRRICA. Derrótalo allí."),
    "TEAM AQUA blocks the cable car on ROUTE 112" to Tr(ja = "112ばんどうろの ロープウェイを アクアだんが ふさいで いる", fr = "La TEAM AQUA bloque le TELEPHERIQUE de la ROUTE 112", de = "TEAM AQUA versperrt die SEILBAHN auf ROUTE 112", it = "Il TEAM IDRO blocca la FUNIVIA sul PERCORSO 112", es = "El EQUIPO AQUA bloquea el TELEFÉRICO de la RUTA 112"),
    "The cave in SOOTOPOLIS CITY." to Tr(ja = "ルネシティの どうくつ。", fr = "La grotte d'ATALANOPOLIS.", de = "Die Höhle in XENEROVILLE.", it = "La grotta di CENERIDE.", es = "La cueva de ARRECÍPOLIS."),
    "End the crisis first: go down through the CAVE OF ORIGIN and face GROUDON at the bottom. WALLACE opens the gym afterwards." to Tr(ja = "まず じけんを おさめよう。 めざめのほこらを おりて いちばん おくの グラードンと むきあう。 その あと ミクリが ジムを あける。", fr = "Mettez d'abord fin à la crise : descendez la GROTTE ORIGINE et affrontez GROUDON tout au fond. MARC ouvre ensuite l'ARENE.", de = "Beende zuerst die Krise: Steig durch die URZEITHÖHLE hinab und stell dich ganz unten GROUDON. Danach öffnet WASSILI die ARENA.", it = "Prima risolvi la crisi: scendi nella GROTTA dei TEMPI e affronta GROUDON in fondo. Poi ADRIANO apre la PALESTRA.", es = "Primero acaba con la crisis: baja por la CUEVA ANCESTRAL y enfréntate a GROUDON al fondo. Después PLUBIO abre el GIMNASIO."),
    "End the crisis first: go down through the CAVE OF ORIGIN and face KYOGRE at the bottom. WALLACE opens the gym afterwards." to Tr(ja = "まず じけんを おさめよう。 めざめのほこらを おりて いちばん おくの カイオーガと むきあう。 その あと ミクリが ジムを あける。", fr = "Mettez d'abord fin à la crise : descendez la GROTTE ORIGINE et affrontez KYOGRE tout au fond. MARC ouvre ensuite l'ARENE.", de = "Beende zuerst die Krise: Steig durch die URZEITHÖHLE hinab und stell dich ganz unten KYOGRE. Danach öffnet WASSILI die ARENA.", it = "Prima risolvi la crisi: scendi nella GROTTA dei TEMPI e affronta KYOGRE in fondo. Poi ADRIANO apre la PALESTRA.", es = "Primero acaba con la crisis: baja por la CUEVA ANCESTRAL y enfréntate a KYOGRE al fondo. Después PLUBIO abre el GIMNASIO."),
    "It's up a waterfall: you need HM07 WATERFALL (in the CAVE OF ORIGIN) and the RAIN BADGE." to Tr(ja = "たきの うえに ある。 ひでんマシン07 たきのぼり (めざめのほこらに ある) と レインバッジが ひつよう。", fr = "Elle est en haut d'une cascade : il faut la CS07 CASCADE (dans la GROTTE ORIGINE) et le BADGE PLUIE.", de = "Es liegt oberhalb eines Wasserfalls: Du brauchst VM07 KASKADE (in der URZEITHÖHLE) und den SCHAUERORDEN.", it = "È in cima a una cascata: servono la MN07 CASCATA (nella GROTTA dei TEMPI) e la MEDAGLIA PIOGGIA.", es = "Está en lo alto de una cascada: necesitas la MO07 CASCADA (en la CUEVA ANCESTRAL) y la MEDALLA LLUVIA."),

    // NEXT BOSS
    "LEADER WALLACE" to Tr(ja = "ジムリーダー ミクリ", fr = "CHAMPION MARC", de = "ARENALEITER WASSILI", it = "CAPOPALESTRA ADRIANO", es = "LÍDER PLUBIO"),
    "CHAMPION STEVEN" to Tr(ja = "チャンピオン ダイゴ", fr = "MAITRE PIERRE", de = "CHAMP TROY", it = "CAMPIONE ROCCO", es = "CAMPEÓN MÁXIMO"),

    // HERE: buildings only Ruby / Sapphire's area data has.
    "CONTEST LOBBY" to Tr(ja = "コンテストかいじょうの ロビー", fr = "le hall de la SALLE DE CONCOURS", de = "dem Foyer der WETTBEWERBSHALLE", it = "atrio delle GARE POKéMON", es = "el vestíbulo de la SALA de CONCURSOS"),
    "CONTEST HALL" to Tr(ja = "コンテストかいじょう", fr = "la SALLE DE CONCOURS", de = "der WETTBEWERBSHALLE", it = "sala delle GARE POKéMON", es = "la SALA de CONCURSOS"),
    "HOUSE 8" to Tr(ja = "8けんめの いえ", fr = "la MAISON 8", de = "dem HAUS 8", it = "CASA 8", es = "la CASA 8"),
    "B3F" to Tr(ja = "ちか3かい", fr = "le 3e sous-sol", de = "dem 3. Untergeschoss", it = "3º sotterraneo", es = "el sótano 3"),
)
