package com.pokedaisey.app.companion.ui

// GENERATED by scripts/gen_cfru_party_assets.py from the Unbound / Radical
// Red / Odyssey / Amethyst ROMs - do not hand-edit; rerun the script instead.

/** The shared CFRU party slot (identical frame, font and layout in all four ROMs). */
private fun cfruPartyStyle(statusAsset: String, pokeballAsset: String?, eggName: String) = PartySlotStyle(
    frameDir = "partycfru",
    fontAsset = "partyfr/font_small.png",
    statusAsset = statusAsset,
    pokeballAsset = pokeballAsset,
    glyphWidths = FireRedPartyStyle.glyphWidths,
    lvGlyph = 0x105,
    padGlyph = 0x00,
    text = 0xFFFFFFFF, textShadow = 0xFF737373,
    male = 0xFF00EFFF, maleShadow = 0xFF006B63,
    female = 0xFFE73939, femaleShadow = 0xFF732131,
    hpGreenTop = 0xFF18C621, hpGreen = 0xFF63FF63,
    hpYellowTop = 0xFFEFAD00, hpYellow = 0xFFFFDE00,
    hpRedTop = 0xFFFF4A39, hpRed = 0xFFFF9C9C,
    hpEmptyTop = 0xFF212121, hpEmpty = 0xFF737373,
    slotW = 112, slotH = 40,
    nameX = 40, nameY = 5,
    levelX = 5, levelY = 25,
    genderX = 98, genderY = 5,
    hpX = 59, maxHpX = 74, hpY = 25,
    barX = 56, barY = 22, barW = 48,
    // Sprite centres (sPartyMenuSpriteCoords) -> top-left, window-relative.
    iconX = 34 - 16 - 8, iconY = 12 - 16 - 0,
    // AnimateSelectedPartyIcon: an icon not at x 16 rests 4px LEFT.
    iconRestDx = -4, iconRestDy = 0,
    ballX = 24 - 16 - 8, ballY = 16 - 16 - 0,
    ballFollowsIcon = true,
    statusX = 26 - 16 - 8, statusY = 33 - 4 - 0,
    leftCol = 60, midCol = 60,
    topRow = 8, midRow = 19, bottomRow = 32, stretchRows = true,
    band = DiagonalBand(
        top = 4, bottom = 37,
        leftTopX = 43, leftBottomX = 10,
        rightTopX = 99, rightBottomX = 66,
        emptyStripeRow = 20,
    ),
    visibleW = 111, visibleH = 40,
    regionX0 = 0, regionY0 = 12 - 16 - 0,
    eggName = eggName,
    upperCaseNames = false,
    hasEmptySlot = true,
    blendOverBackdrop = true,
)

val UnboundPartyStyle = cfruPartyStyle(
    statusAsset = "partycfru/ub/status_icons.png",
    pokeballAsset = "partycfru/ub/pokeball.png",
    eggName = "Egg",
)

val RadicalRedPartyStyle = cfruPartyStyle(
    statusAsset = "partycfru/rr/status_icons.png",
    pokeballAsset = null,
    eggName = "Egg",
)

val OdysseyPartyStyle = cfruPartyStyle(
    statusAsset = "partycfru/od/status_icons.png",
    pokeballAsset = null,
    eggName = "EGG",
)

val AmethystPartyStyle = cfruPartyStyle(
    statusAsset = "partycfru/am/status_icons.png",
    pokeballAsset = null,
    eggName = "Egg",
)
